const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
const backend=new Function('require','__dirname',read('tests/transversales.test.cjs').split('\ntest(')[0]+'\nreturn fixture;')(require,__dirname);
function raw(s,n=12){const c=s.c.registroEvaluacion_(),session={fecha:'2026-10-14',comp:'tic',capacidad:c.CAPS.tic[0]};return {schema:1,sessions:[session],grades:{[c.sessionKey(session)]:{[s.id]:{modo:'num',valor:n}}},directos:{}};}
function own(s){return s.load('math').aportes.find(a=>a.user==='math');}
function save(s,e,extra={}){return s.route('savetransversalaporte','math',{area:'Matemática',version:own(s)?.version||0,evidencia:e,...extra});}
function direct(s,value,modo=typeof value==='number'?'num':'letra'){const e=own(s)?clone(own(s).evidencia):raw(s);e.directos={[s.id]:{tic:{modo,valor:value}}};return save(s,e);}
function extract(name){const text=read('registro.html'),i=text.search(new RegExp('(?:async )?function '+name+'\\('));assert.ok(i>=0,name);const line=text.slice(i).split('\n')[0];return line.endsWith('}')?line:text.slice(i,text.indexOf('\n}',i)+2);}
function ui(){
 const s=backend(),els=new Map(),events={};let paints=0;const el=id=>{if(!els.has(id))els.set(id,{value:id==='inpFecha'?'2026-10-14':'',innerHTML:'',textContent:'',children:[],style:{},classList:{contains:()=>false,add(){},remove(){},toggle(){}},appendChild(x){this.children.push(x)},querySelectorAll:()=>[],querySelector:()=>null});return els.get(id);};
 const calls=[],c=vm.createContext({window:null,document:{getElementById:el,querySelectorAll:()=>[],createElement:tag=>({...el('created-'+els.size),tagName:tag}),activeElement:null},console,Date,Map,Set,JSON,confirm:()=>true,addEventListener:(type,f)=>events[type]=f});c.window=c;
 vm.runInContext(read('registro-evaluation.js'),c);
 const signed=s.token('math');c.IEStudents={validToken:()=>signed};c.IETransversales={request:async(action,p)=>{calls.push({action,...clone(p)});const out=s.route(action,'math',p);if(!out.ok)throw Object.assign(Error(out.error),{code:out.code});return clone(out)}};
 c.getLoginSession=()=>({role:'docente',user:'math'});c.ctxBase=()=>({nivel:c.nivel,bim:c.bim,grado:c.grado,seccion:c.seccion,area:c.areaActual});c.estudiantes=()=>s.roster.filter(a=>a.seccion==='A');c.studentKey=a=>'id:'+encodeURIComponent(a.idSiagie);c.registroSoloLectura=()=>false;c.bimCerradoDocente=()=>false;c.registroNubeNoVerificada=()=>false;c.renderStudents=c.renderSesiones=c.renderFinales=c.renderAvance=()=>paints++;c.loadCapsElegidas=()=>{};c.competencias=()=>['Académica'];c.toast=m=>el('toast').textContent=m;
 Object.assign(c,{nivel:'secundaria',bim:'I',grado:2,seccion:'A',areaActual:'Matemática',modoCalif:'num',capsElegidas:[],store:{sessions:[],grades:{},finales:{},capsSel:{},meta:{},concArea:{}}});
 ['claveCompetenciaTransversal','esCompetenciaTransversal','competenciasParaEvaluar','capsOficiales','fillCaps','fillComps','normCapItem','tieneCapSel','keyCapsHoy','loadCapsElegidas','saveCapsElegidas','upsertSesionCap'].forEach(n=>vm.runInContext(extract(n),c));
 c.CAPS_CNEB={Académica:['Capacidad académica']};c.saveStore=()=>{};c.hoyISO=()=> '2026-10-14';c.sessionId=x=>JSON.stringify(x);c.loadCapsElegidas=()=>{};
 vm.runInContext(read('registro-transversales.js'),c);
 return {s,c,el,calls,events,api:c.IERegistroTransversales,run:code=>vm.runInContext(code,c),paints:()=>paints};
}

test('Backend retains calculated B and exposes effective direct A and its origin',()=>{const s=backend();assert.equal(save(s,raw(s)).ok,true);const before=clone(own(s).evidencia.grades);assert.equal(direct(s,'A').ok,true);const a=own(s);assert.equal(a.calculados[s.id].tic.nivel,'B');assert.equal(a.valores[s.id].tic.nivel,'A');assert.equal(a.origenes[s.id].tic,'directo');assert.deepEqual(clone(a.evidencia.grades),before);assert.equal(s.tables.get('RegistroNotas').rows.length,1);});
test('Deleting the direct override restores calculated evidence without deleting grades',()=>{const s=backend();save(s,raw(s));direct(s,'A');const e=clone(own(s).evidencia);e.directos={};assert.equal(save(s,e).ok,true);assert.equal(own(s).valores[s.id].tic.nivel,'B');assert.equal(own(s).origenes[s.id].tic,'evidencias');assert.equal(own(s).evidencia.sessions.length,1);});
for(const [v,level,n] of [[0,'C',0],[13.5,'A',14],[20,'AD',20],['AD','AD',undefined],['A','A',undefined],['B','B',undefined],['C','C',undefined]])test('Direct '+v+' uses unchanged rounding/letter semantics',()=>{const s=backend(),out=direct(s,v);assert.equal(out.ok,true,out.error);const a=own(s).valores[s.id].tic;assert.equal(a.nivel,level);assert.equal(a.nota20,n);});
for(const v of [-0.2,20.1,Infinity,'invalid'])test('Direct '+v+' is rejected before rounding and cannot create an append',()=>{const s=backend(),before=s.state.writes;assert.equal(direct(s,v).ok,false);assert.equal(s.state.writes,before);});
test('Forged direct final fields are recomputed by server',()=>{const s=backend(),e=raw(s);e.directos={[s.id]:{tic:{modo:'num',valor:13.5,nota20:20,nivel:'AD'}}};assert.equal(save(s,e).ok,true);assert.equal(own(s).valores[s.id].tic.nivel,'A');assert.equal(own(s).valores[s.id].tic.nota20,14);});
for(const q of ['student','competence','array'])test('Backend rejects forged direct '+q,()=>{const s=backend(),e=raw(s);e.directos=q==='student'?{'id:foreign':{tic:{modo:'letra',valor:'A'}}}:q==='competence'?{[s.id]:{academic:{modo:'letra',valor:'A'}}}:[];assert.equal(save(s,e).code,'VALIDATION');});
test('Historical schema1 without directos reads unchanged without a migration',()=>{const s=backend(),e=raw(s);delete e.directos;assert.equal(save(s,e).ok,true);assert.equal(own(s).origenes[s.id].tic,'evidencias');const rows=JSON.stringify(s.tables.get('TransversalesAportes').rows);s.load('pip');assert.equal(JSON.stringify(s.tables.get('TransversalesAportes').rows),rows);});
test('Older clients omitting directos preserve an existing override; explicit empty block removes it',()=>{const s=backend();direct(s,'AD');const e=clone(own(s).evidencia);delete e.directos;save(s,e);assert.equal(own(s).valores[s.id].tic.nivel,'AD');e.directos={};save(s,e);assert.equal(own(s).valores[s.id].tic.nivel,'B');});
for(const action of ['A-to-15','delete'])test(action+' invalidates Tutor/AIP even with unchanged effective A and preserves history',()=>{const s=backend();save(s,raw(s,15));direct(s,'A');s.final('math','A');s.confirm('math','confirmtransversaltutor');s.confirm('pip','confirmtransversalaip');const before=s.load('pip'),rows=JSON.stringify(s.tables.get('TransversalesAportes').rows);if(action==='A-to-15')direct(s,15);else{const e=clone(own(s).evidencia);e.directos={};save(s,e);}const after=s.load('pip');assert.equal(after.resultados[s.id].tic.listo,false);assert.match(after.resultados[s.id].tic.estado,/Requiere nueva confirmación/);assert.notEqual(after.versionAportes,before.versionAportes);assert.equal(own(s).valores[s.id].tic.nivel,'A');assert.equal(JSON.stringify(s.tables.get('TransversalesAportes').rows.slice(0,-1)),rows);});
test('CONFLICT never appends or replaces a direct contribution',()=>{const s=backend();direct(s,'A');const original=JSON.stringify(s.tables.get('TransversalesAportes').rows);assert.equal(save(s,raw(s),{version:0}).code,'CONFLICT');assert.equal(JSON.stringify(s.tables.get('TransversalesAportes').rows),original);});
for(const user of ['pip','admin','auxiliar','communication','other'])test(user+' cannot impersonate Math to change a direct contribution',()=>{const s=backend(),e=raw(s);e.directos={[s.id]:{tic:{modo:'letra',valor:'A'}}};assert.equal(s.route('savetransversalaporte',user,{area:'Matemática',version:0,evidencia:e,user:'math',docente:'math'}).ok,false);});
for(const period of ['cerrado','bloqueado'])test(period+' forbids saving direct, clearing direct and confirmation',()=>{const s=backend();direct(s,'A');s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({bimestres:{I:period}});assert.equal(direct(s,'B').code,'PERIOD');assert.equal(save(s,{schema:1,sessions:[],grades:{},directos:{}}).code,'PERIOD');assert.equal(s.confirm('math','confirmtransversaltutor').code,'PERIOD');assert.equal(own(s).valores[s.id].tic.nivel,'A');});
test('Tutor and AIP receive exactly one effective vote per area with original evidence',()=>{const s=backend();save(s,raw(s));direct(s,'AD');const out=s.load('pip'),a=out.resultados[s.id].tic.resumen.aportes;assert.equal(a.length,1);assert.equal(a[0].valor.nivel,'AD');assert.equal(a[0].origen,'directo');assert.equal(out.aportes[0].evidencia.sessions.length,1);});
test('Direct C still requires descriptive conclusion on consolidated C, and Admin cannot confirm',()=>{const s=backend();direct(s,'C');s.final('math','C');assert.equal(s.confirm('math','confirmtransversaltutor').ok,false);assert.equal(s.confirm('admin','confirmtransversaltutor').ok,false);assert.equal(s.confirm('admin','confirmtransversalaip').ok,false);assert.equal(s.route('loadtransversalexport','admin').resultados[s.id].tic.listo,false);});

test('Secondary selector groups academics before transversals without extending competencias()',()=>{const f=ui();f.c.fillComps();const html=f.el('selComp').innerHTML;assert.ok(html.indexOf('Competencias del área')<html.indexOf('Competencias transversales'));assert.equal(f.c.competencias().length,1);assert.equal(f.c.competenciasParaEvaluar().length,3);});
test('Primary selector and academic capabilities keep Otra and no transversal options',()=>{const f=ui();f.c.nivel='primaria';f.c.fillComps();assert.doesNotMatch(f.el('selComp').innerHTML,/transversales/);f.el('selComp').value='Académica';f.c.fillCaps();assert.match(f.el('selCap').innerHTML,/Otra \(escribir\)/);assert.equal(f.c.competenciasParaEvaluar().length,1);});
for(const [comp,n] of [['tic',4],['autonomia',3]])test(comp+' uses exactly official '+n+' capabilities and never Otra',()=>{const f=ui();f.el('selComp').value=f.c.IERegistroEvaluacion.COMP[comp];f.c.fillCaps();const html=f.el('selCap').innerHTML;assert.doesNotMatch(html,/__otra__/);assert.equal((html.match(/<option/g)||[]).length,n+1);assert.deepEqual(clone(f.c.capsOficiales(f.el('selComp').value)),clone(f.c.IERegistroEvaluacion.CAPS[comp]));});
test('Capability columns explicitly track academic/transversal origin',()=>{const f=ui();assert.equal(f.c.normCapItem({comp:'Académica',cap:'Cap'}).origen,'academica');assert.equal(f.c.normCapItem({comp:f.c.IERegistroEvaluacion.COMP.tic,cap:'Cap'}).origen,'transversal');});
test('A shared date unifies columns/sessions without writing transversal sessions or selection to academic store',async()=>{const f=ui();await f.api.load();const comp=f.c.IERegistroEvaluacion.COMP.tic,cap=f.c.IERegistroEvaluacion.CAPS.tic[0];assert.equal(f.c.upsertSesionCap(comp,cap),true);assert.equal(f.c.store.sessions.length,0);f.c.upsertSesionCap('Académica','Cap');assert.equal(f.c.store.sessions.length,1);f.c.capsElegidas=[f.c.normCapItem({comp:'Académica',cap:'Cap'}),f.api.columns('2026-10-14')[0]];f.c.saveCapsElegidas();assert.equal(f.c.store.capsSel[f.c.keyCapsHoy()].length,1);assert.equal(f.api.sessions()[0].fecha,f.c.store.sessions[0].fecha);});
test('Shared grid draws a transversal cell and never includes academic grade keys in its evidence',async()=>{const f=ui();await f.api.load();const comp=f.c.IERegistroEvaluacion.COMP.tic,cap=f.c.IERegistroEvaluacion.CAPS.tic[0];f.api.add(comp,cap,'2026-10-14');const html=f.api.cell(f.s.roster[0],f.api.columns('2026-10-14')[0],'2026-10-14');assert.match(html,/trans-nota/);assert.doesNotMatch(html,/class="cal-nota"/);assert.deepEqual(clone(f.c.store.grades),{});});
test('Direct override/deletion updates preview while keeping calculated grades intact',async()=>{const f=ui();save(f.s,raw(f.s));await f.api.load();const e=f.api.current(),id=f.s.id;assert.equal(f.api.result().valores[id].tic.nivel,'B');f.api.setDirect(e,id,'tic',{modo:'letra',valor:'A'});assert.equal(f.api.result().valores[id].tic.nivel,'A');assert.equal(f.api.result().calculados[id].tic.nivel,'B');f.api.setDirect(e,id,'tic',{modo:'num',valor:''});assert.equal(f.api.result().valores[id].tic.nivel,'B');assert.equal(Object.keys(e.evidence.grades).length,1);assert.deepEqual(clone(f.c.store.finales),{});});
test('One save sends the complete area block including both direct competences',async()=>{const f=ui();await f.api.load();const e=f.api.current();for(const comp of ['tic','autonomia'])f.api.setDirect(e,f.s.id,comp,{modo:'num',valor:17});assert.equal(await f.api.save(),true);const writes=f.calls.filter(c=>c.action==='savetransversalaporte');assert.equal(writes.length,1);assert.equal(Object.keys(writes[0].evidencia.directos[f.s.id]).length,2);assert.equal(e.dirty,false);});
test('Network failure preserves dirty draft, reports partial save and academic functions remain callable',async()=>{const f=ui();await f.api.load();const e=f.api.current();f.api.setDirect(e,f.s.id,'tic',{modo:'letra',valor:'A'});f.c.IETransversales.request=async()=>{throw Error('synthetic offline')};assert.equal(await f.api.save(),false);assert.equal(e.dirty,true);assert.equal(e.evidence.directos[f.s.id].tic.nivel,'A');assert.match(f.el('registroTransStatus').textContent,/notas del área se guardaron localmente.*Reintenta/);f.c.upsertSesionCap('Académica','Cap');assert.equal(f.c.store.sessions.length,1);});
test('Changing area and returning restores dirty draft without reloading/overwriting it',async()=>{const f=ui();await f.api.load();const e=f.api.current();f.api.setDirect(e,f.s.id,'tic',{modo:'letra',valor:'A'});f.c.areaActual='Comunicación';await f.api.load();f.c.areaActual='Matemática';await f.api.load();assert.equal(f.api.current(),e);assert.equal(e.dirty,true);assert.equal(e.evidence.directos[f.s.id].tic.nivel,'A');});
test('Late load from another context cannot replace the visible draft',async()=>{const f=ui();let resolve;const original=f.c.IETransversales.request;f.c.IETransversales.request=()=>new Promise(r=>resolve=r);const pending=f.api.load();f.c.areaActual='Comunicación';f.c.IETransversales.request=original;await f.api.load();const before=f.paints();resolve(clone(f.s.load('math')));await pending;assert.equal(f.paints(),before);assert.equal(f.api.current().ctx.area,'Comunicación');});
test('A late save keeps edits made while saving and advances optimistic version',async()=>{const f=ui();await f.api.load();const e=f.api.current();f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:14});let release;const original=f.c.IETransversales.request;f.c.IETransversales.request=(a,p)=>new Promise(r=>release=async()=>r(await original(a,p)));const task=f.api.save();f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:18});await release();await task;assert.equal(e.dirty,true);assert.equal(e.evidence.directos[f.s.id].tic.valor,18);assert.ok(e.version>0);});
test('Concurrent save clicks share one operation and CONFLICT never cleans or overwrites draft',async()=>{const f=ui();await f.api.load();const e=f.api.current();f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:14});let reject,n=0;f.c.IETransversales.request=()=>{n++;return new Promise((r,j)=>reject=j)};const a=f.api.save(),b=f.api.save();reject({code:'CONFLICT'});assert.equal(await a,false);assert.equal(await b,false);assert.equal(n,1);assert.equal(e.dirty,true);assert.match(f.el('registroTransStatus').textContent,/CONFLICT/);});
test('Closed period keeps evidence/direct preview but disables edit, removal and save',async()=>{const f=ui();direct(f.s,'A');f.s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({bimestres:{I:'cerrado'}});await f.api.load();const e=f.api.current();assert.equal(f.api.editable(),false);assert.equal(f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:''}),false);assert.equal(f.api.add(f.c.IERegistroEvaluacion.COMP.tic,f.c.IERegistroEvaluacion.CAPS.tic[1],'2026-10-14'),false);assert.equal(f.api.result().valores[f.s.id].tic.nivel,'A');});
test('Failed transversal load cannot gate academic rendering and exposes recovery',async()=>{const f=ui();f.c.IETransversales.request=async()=>{throw Error('offline')};await f.api.load();assert.match(f.el('registroTransStatus').textContent,/Las áreas académicas siguen disponibles/);f.c.upsertSesionCap('Académica','Cap');assert.equal(f.c.store.sessions.length,1);});
test('Beforeunload warns about unsaved transversal drafts rather than silently losing them',async()=>{const f=ui();await f.api.load();f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'num',valor:17});let blocked=false;const event={preventDefault:()=>blocked=true};f.events.beforeunload(event);assert.equal(blocked,true);assert.equal(event.returnValue,'');});
test('Resumen displays both effective transversals and source without changing academic conclusions',async()=>{const f=ui();save(f.s,raw(f.s));await f.api.load();f.api.setDirect(f.api.current(),f.s.id,'autonomia',{modo:'letra',valor:'A'});const root=f.el('summary');f.api.summary(root);const html=root.children[0].innerHTML;assert.match(html,/APORTE DE COMPETENCIAS TRANSVERSALES DEL ÁREA/);assert.match(html,/TIC/);assert.match(html,/Gestión autónoma/);assert.match(html,/Promedio directo/);assert.match(html,/Evidencias/);assert.deepEqual(clone(f.c.store.concArea),{});});
test('Academic average/conclusion/SIAGIE functions still use only competencias()',()=>{const s=read('registro.html');for(const name of ['validarConclusionesOficial','informeSiagie','renderAvance']){const source=extract(name);assert.doesNotMatch(source,/competenciasParaEvaluar\(/);}assert.match(s,/function competencias\(\)[\s\S]*e\.competencias/);assert.doesNotMatch(read('registro-transversales.js'),/store\.grades\s*=|store\.finales\s*=|CacheStorage|localStorage\.setItem|caches\.open/);});
test('Late transversal paint flushes current academic inputs before rebuilding any grid',async()=>{const f=ui();let saved=0;f.c.guardarTodo=()=>{saved++;return true};await f.api.load();assert.equal(saved,1);assert.ok(f.paints()>0);});
test('Academic local storage failure prevents late repaint and preserves the visible draft',async()=>{const f=ui();f.c.guardarTodo=()=>false;await f.api.load();assert.equal(f.paints(),0);assert.match(f.el('registroTransStatus').textContent,/conservar el trabajo académico/);});
test('Promedios appends exactly two transversal columns after academic headers and binds only separate controls',async()=>{
 const f=ui();save(f.s,raw(f.s));await f.api.load();f.api.setDirect(f.api.current(),f.s.id,'autonomia',{modo:'letra',valor:'A'});
 const headers=[{html:'academic',insertAdjacentHTML(where,text){this.html+=text}}],row={html:'',insertAdjacentHTML(where,text){this.html+=text}};
 const thead={firstChild:headers[0],insertBefore(x){headers.unshift(x)},querySelectorAll:()=>headers};
 const table={querySelector:()=>thead,querySelectorAll:()=>[row]},root={querySelector:()=>table,querySelectorAll:()=>[]};f.api.finals(root);
 assert.match(headers[0].innerHTML,/COMPETENCIAS TRANSVERSALES — APORTE DEL ÁREA/);assert.match(headers[1].html,/academic.*TIC.*Gestiona su aprendizaje/);assert.equal((row.html.match(/<td>/g)||[]).length,2);assert.match(row.html,/Cal 12 · B/);assert.doesNotMatch(row.html,/data-fin|class="fin-nota"/);
});
test('Unverified roster blocks transversal backend writes without dropping a local draft',async()=>{const f=ui();await f.api.load();f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'letra',valor:'A'});f.c.registroNubeNoVerificada=()=>true;assert.equal(await f.api.save(),false);assert.equal(f.api.current().dirty,true);assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);});
test('Explicit SESSION refusal disables transversal edits while retaining unsaved memory for recovery',async()=>{const f=ui();await f.api.load();const e=f.api.current();f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:17});f.c.IETransversales.request=async()=>{throw {code:'SESSION'}};assert.equal(await f.api.save(),false);assert.equal(f.api.editable(e),false);assert.equal(e.dirty,true);});
test('Actual Calificar reuses stuList for mixed academic/transversal columns, no second table or cross-store grades',async()=>{
 const f=ui();await f.api.load();const comp=f.c.IERegistroEvaluacion.COMP.tic,cap=f.c.IERegistroEvaluacion.CAPS.tic[0];f.api.add(comp,cap,'2026-10-14');f.c.capsElegidas=[f.c.normCapItem({comp:'Académica',cap:'Cap'}),...f.api.columns('2026-10-14')];
 Object.assign(f.c,{colsCalificar:()=>f.c.capsElegidas,capKeyHoy:()=> 'academic-key',leerNota:(map,key)=>map[key],pad2:n=>String(n),numToLetter:f.c.IERegistroEvaluacion.numToLetter,eqClass:()=>'',actualizarContadores:()=>{},sincronizarEdicionRegistro:()=>{}});
 f.c.store.grades['academic-key']={nota20:15,nivel:'A'};vm.runInContext(extract('renderStudents'),f.c);f.c.renderStudents();const html=f.el('stuList').innerHTML;assert.equal((html.match(/<table/g)||[]).length,1);assert.match(html,/Académica/);assert.match(html,/entornos virtuales/);assert.match(html,/cal-nota/);assert.match(html,/trans-nota/);assert.deepEqual(Object.keys(f.c.store.grades),['academic-key']);
});
test('Invalid direct input stays recoverable and blocks save instead of claiming success',async()=>{const f=ui();await f.api.load();const e=f.api.current();assert.equal(f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:20.1}),false);assert.equal(e.dirty,true);assert.equal(await f.api.save(),false);assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);assert.match(f.el('registroTransStatus').textContent,/inválidas/);assert.equal(f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:13.5}),true);assert.equal(await f.api.save(),true);assert.equal(own(f.s).valores[f.s.id].tic.nivel,'A');});
test('Old PR62 backend capability cannot silently discard overrides during staged publication',async()=>{const f=ui(),original=f.c.IETransversales.request;f.c.IETransversales.request=async(a,p)=>{const data=await original(a,p);delete data.soportaDirectos;return data};await f.api.load();assert.equal(f.api.editable(),false);assert.match(f.el('registroTransStatus').textContent,/backend aún no admite/);assert.equal(f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'num',valor:17}),false);f.c.upsertSesionCap('Académica','Cap');assert.equal(f.c.store.sessions.length,1);});
test('Returning to a clean context refreshes the server version rather than treating memory as truth',async()=>{const f=ui();await f.api.load();f.c.areaActual='Comunicación';await f.api.load();direct(f.s,'AD');f.c.areaActual='Matemática';await f.api.load();assert.equal(f.api.result().valores[f.s.id].tic.nivel,'AD');assert.equal(f.calls.filter(c=>c.action==='loadtransversales'&&c.area==='Matemática').length,2);});
test('Refreshing a dirty context detects remote conflict and never overwrites unsaved direct values',async()=>{const f=ui();await f.api.load();const e=f.api.current();f.api.setDirect(e,f.s.id,'tic',{modo:'letra',valor:'A'});f.c.areaActual='Comunicación';await f.api.load();direct(f.s,'AD');f.c.areaActual='Matemática';await f.api.load();assert.equal(e.evidence.directos[f.s.id].tic.nivel,'A');assert.equal(e.dirty,true);assert.match(f.el('registroTransStatus').textContent,/CONFLICT/);});
test('A direct bimestral contribution is accepted with no daily evidence at all',()=>{const s=backend(),e={schema:1,sessions:[],grades:{},directos:{[s.id]:{tic:{modo:'num',valor:17},autonomia:{modo:'letra',valor:'AD'}}}};assert.equal(save(s,e).ok,true);const a=own(s);assert.deepEqual(clone(a.calculados[s.id]),{});assert.equal(a.valores[s.id].tic.nivel,'A');assert.equal(a.valores[s.id].autonomia.nivel,'AD');assert.equal(a.origenes[s.id].tic,'directo');assert.equal(a.evidencia.sessions.length,0);});
test('Viewing a saved letter in numeric mode never changes its mode or creates a new version',async()=>{const f=ui();direct(f.s,'A');await f.api.load();const e=f.api.current(),version=e.version;f.c.document.querySelectorAll=()=>[{value:'15',readOnly:false,dataset:{transEntry:String(e.id),transId:f.s.id,transComp:'tic'}}];assert.equal(await f.api.save(),true);assert.equal(e.evidence.directos[f.s.id].tic.modo,'letra');assert.equal(e.version,version);assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);});
test('Removing a capacity also clears its invalid draft so saving never becomes unrecoverable',async()=>{const f=ui();await f.api.load();const comp=f.c.IERegistroEvaluacion.COMP.tic,cap=f.c.IERegistroEvaluacion.CAPS.tic[0];f.api.add(comp,cap,'2026-10-14');const e=f.api.current(),key=f.c.IERegistroEvaluacion.sessionKey(e.evidence.sessions[0]),inp={value:'21',dataset:{transId:f.s.id,transComp:'tic',transKey:key}};f.api.bind({querySelectorAll:sel=>sel.includes('.trans-nota')?[inp]:[]});inp.oninput();assert.ok(Object.keys(e.invalid).length);assert.equal(f.api.remove(comp,cap,'2026-10-14'),true);assert.equal(Object.keys(e.invalid).length,0);assert.equal(await f.api.save(),true);});

function finalHtml(f){
 const headers=[{insertAdjacentHTML(){}}],row={html:'',insertAdjacentHTML(where,text){this.html+=text}};
 const thead={firstChild:headers[0],insertBefore(x){headers.unshift(x)},querySelectorAll:()=>headers};
 const table={querySelector:()=>thead,querySelectorAll:()=>[row]};f.api.finals({querySelector:()=>table,querySelectorAll:()=>[]});return row.html;
}
function clickDirect(f,value){const button={dataset:{transVal:value},parentElement:{dataset:{transId:f.s.id,transComp:'tic'}}};f.api.bind({querySelectorAll:sel=>sel==='[data-trans-val]'?[button]:[]});button.onclick();}
test('Calculated B is highlighted in letters with Cal B and no direct override or removal control',async()=>{
 const f=ui();save(f.s,raw(f.s));await f.api.load();f.c.modoCalif='letra';const html=finalHtml(f);
 assert.match(html,/nivel-b on/);assert.match(html,/<small>Cal B<\/small>/);assert.doesNotMatch(html,/Quitar directo/);assert.deepEqual(clone(f.api.current().evidence.directos),{});
});
test('Changing letters/numeric views of calculated B never creates a direct or version',async()=>{
 const f=ui();save(f.s,raw(f.s));await f.api.load();const e=f.api.current(),version=e.version,rows=f.s.tables.get('TransversalesAportes').rows.length;
 for(const mode of ['letra','num','letra','num']){f.c.modoCalif=mode;const html=finalHtml(f);if(mode==='num'){assert.match(html,/trans-direct-num[^>]*value=""/);assert.match(html,/Cal 12 · B/);}await f.api.save();}
 assert.deepEqual(clone(e.evidence.directos),{});assert.equal(e.dirty,false);assert.equal(e.revision,0);assert.equal(e.version,version);assert.equal(f.s.tables.get('TransversalesAportes').rows.length,rows);assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);
});
test('Explicitly clicking calculated B creates a direct B decision',async()=>{const f=ui();save(f.s,raw(f.s));await f.api.load();f.c.modoCalif='letra';clickDirect(f,'B');assert.equal(f.api.current().dirty,true);assert.equal(f.api.current().evidence.directos[f.s.id].tic.modo,'letra');assert.equal(await f.api.save(),true);assert.equal(own(f.s).origenes[f.s.id].tic,'directo');});
for(const [mode,value] of [['letra','A'],['num',15]])test('Repeating direct '+mode+' '+value+' is no-op including actual input/click and save',async()=>{
 const f=ui();direct(f.s,value,mode);await f.api.load();const e=f.api.current(),version=e.version,rows=f.s.tables.get('TransversalesAportes').rows.length,conf=f.s.load('pip').versionAportes;
 if(mode==='letra')clickDirect(f,value);else{const inp={value:'15',dataset:{transId:f.s.id,transComp:'tic'}};f.api.bind({querySelectorAll:sel=>sel.includes('.trans-nota')?[inp]:[]});inp.oninput();inp.onchange();}
 assert.equal(e.dirty,false);assert.equal(e.revision,0);await f.api.save();assert.equal(e.version,version);assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);assert.equal(f.s.tables.get('TransversalesAportes').rows.length,rows);assert.equal(f.s.load('pip').versionAportes,conf);
});
for(const [mode,value] of [['letra','A'],['num',14]])test('Direct '+mode+' '+value+' to numeric 15 changes original value/mode and appends version',async()=>{
 const f=ui();direct(f.s,value,mode);await f.api.load();const e=f.api.current(),version=e.version,rows=f.s.tables.get('TransversalesAportes').rows.length;
 assert.equal(f.api.setDirect(e,f.s.id,'tic',{modo:'num',valor:15}),true);assert.equal(e.dirty,true);assert.equal(e.revision,1);assert.equal(await f.api.save(),true);assert.ok(e.version>version);assert.equal(f.s.tables.get('TransversalesAportes').rows.length,rows+1);assert.equal(own(f.s).evidencia.directos[f.s.id].tic.valor,15);
});
test('Removing a nonexistent direct is no-op without empty structures, append or confirmation invalidation',async()=>{
 const f=ui();save(f.s,raw(f.s));await f.api.load();const e=f.api.current(),version=e.version,stamp=f.s.load('pip').versionAportes,rows=f.s.tables.get('TransversalesAportes').rows.length;
 assert.equal(f.api.setDirect(e,f.s.id,'tic',{modo:'letra',valor:''}),false);assert.equal(e.dirty,false);assert.equal(e.revision,0);assert.deepEqual(clone(e.evidence.directos),{});await f.api.save();assert.equal(e.version,version);assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);assert.equal(f.s.tables.get('TransversalesAportes').rows.length,rows);assert.equal(f.s.load('pip').versionAportes,stamp);
});
for(const mode of ['letra','num'])test('Quitar directo appears only for actual overrides in '+mode+' mode',async()=>{const f=ui();save(f.s,raw(f.s));await f.api.load();f.c.modoCalif=mode;assert.doesNotMatch(finalHtml(f),/Quitar directo/);f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'letra',valor:'A'});assert.equal((finalHtml(f).match(/Quitar directo/g)||[]).length,1);});
test('Removing existing direct cleans empty student entry, restores B and invalidates Tutor/AIP confirmations',async()=>{
 const f=ui();save(f.s,raw(f.s));direct(f.s,'A');f.s.final('math','A');f.s.confirm('math','confirmtransversaltutor');f.s.confirm('pip','confirmtransversalaip');await f.api.load();clickDirect(f,'');const e=f.api.current();assert.deepEqual(clone(e.evidence.directos),{});assert.equal(f.api.result().valores[f.s.id].tic.nivel,'B');assert.equal(e.revision,1);assert.equal(await f.api.save(),true);assert.equal(f.s.load('pip').resultados[f.s.id].tic.listo,false);assert.match(f.s.load('pip').resultados[f.s.id].tic.estado,/Requiere nueva confirmación/);
});
test('Removing one direct preserves the other competence for the same student',async()=>{const f=ui();await f.api.load();const e=f.api.current();for(const c of ['tic','autonomia'])f.api.setDirect(e,f.s.id,c,{modo:'letra',valor:'A'});clickDirect(f,'');assert.deepEqual(Object.keys(e.evidence.directos[f.s.id]),['autonomia']);});
test('Normal loading, availability, editing and successful save hide the attention notice',async()=>{
 const f=ui(),request=f.c.IETransversales.request;let resolve;f.c.IETransversales.request=(a,p)=>new Promise(r=>resolve=()=>r(request(a,p)));const pending=f.api.load();assert.equal(f.el('registroTransAviso').hidden,true);resolve();await pending;assert.equal(f.el('registroTransAviso').hidden,true);f.c.IETransversales.request=request;clickDirect(f,'A');assert.equal(f.el('registroTransAviso').hidden,true);await f.api.save();assert.equal(f.el('registroTransAviso').hidden,true);assert.match(f.el('registroTransStatus').textContent,/guardadas/);assert.match(extract('updateHdr'),/IERegistroTransversales.syncStatus\(\)/);
});
test('Network failure shows notice and retry, successful retry hides it without reloading Registro',async()=>{const f=ui(),request=f.c.IETransversales.request;f.c.IETransversales.request=async()=>{throw Error('offline')};await f.api.load();assert.equal(f.el('registroTransAviso').hidden,false);assert.match(read('registro.html'),/IERegistroTransversales.load\(true\).*Reintentar/);f.c.IETransversales.request=request;await f.api.load(true);assert.equal(f.el('registroTransAviso').hidden,true);});
for(const code of ['CONFLICT','SESSION'])test(code+' saving failure displays recoverable notice and keeps unsaved draft',async()=>{const f=ui();await f.api.load();clickDirect(f,'A');f.c.IETransversales.request=async()=>{throw {code}};await f.api.save();assert.equal(f.el('registroTransAviso').hidden,false);assert.equal(f.api.current().dirty,true);if(code==='CONFLICT'){assert.match(f.el('registroTransStatus').textContent,/CONFLICT/);clickDirect(f,'B');assert.equal(f.el('registroTransAviso').hidden,false);}else assert.equal(f.api.editable(),false);});
test('Older backend shows attention notice and keeps academic interface available',async()=>{const f=ui(),request=f.c.IETransversales.request;f.c.IETransversales.request=async(a,p)=>{const data=await request(a,p);delete data.soportaDirectos;return data};await f.api.load();assert.equal(f.el('registroTransAviso').hidden,false);assert.match(f.el('registroTransStatus').textContent,/backend aún no admite/);assert.equal(f.api.editable(),false);});
test('Invalid transversal input shows attention and successful corrected save hides it',async()=>{const f=ui();await f.api.load();f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'num',valor:21});assert.equal(f.el('registroTransAviso').hidden,false);f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'num',valor:15});await f.api.save();assert.equal(f.el('registroTransAviso').hidden,true);});
test('Attention notice follows context and disappears outside eligible Secondary teacher context',async()=>{const f=ui();await f.api.load();clickDirect(f,'A');f.c.IETransversales.request=async()=>{throw {code:'CONFLICT'}};await f.api.save();assert.equal(f.el('registroTransAviso').hidden,false);f.c.areaActual='Otra área';f.api.syncStatus();assert.equal(f.el('registroTransAviso').hidden,true);f.c.areaActual='Matemática';f.api.syncStatus();assert.equal(f.el('registroTransAviso').hidden,false);f.c.nivel='primaria';f.api.syncStatus();assert.equal(f.el('registroTransAviso').hidden,true);});
