const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{execFileSync}=require('node:child_process');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),html=read('registro.html').replace(/\r\n/g,'\n'),old=execFileSync('git',['show','321c72933a69830f1f731514513e21c240e1529c:registro.html'],{cwd:root,encoding:'utf8',maxBuffer:4*1024*1024}).replace(/\r\n/g,'\n');
function extract(name,src=html){const start=src.indexOf('function '+name+'(');assert.ok(start>=0,name);return src.slice(start,src.indexOf('\n}',start)+2);}
function dataUI(){const elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,{value:'',hidden:false,textContent:'',style:{},attrs:{},setAttribute(k,v){this.attrs[k]=v;}});return elements.get(id);};for(const [id,value]of Object.entries({selBim:'III',selGrado:'2',selSeccion:'A'}))el(id).value=value;
 const c=vm.createContext({document:{getElementById:el},nivel:'secundaria',areaActual:'Matemática',registroSoloLectura:()=>false,estudiantes:()=>[{}],getLoginSession:()=>({role:'docente',label:'Synthetic Teacher'}),ctxBase:()=>({nivel:'secundaria',bim:'III',grado:2,seccion:'A',area:'Matemática'}),nombreDocenteTexto:v=>String(v||''),docenteAsignadoAdmin:()=> 'Assigned Admin Teacher',store:{meta:{}},dirty:false});vm.runInContext('let datosRegistroEleccion=null;'+['pintarEstadoDatosRegistro','alternarDatosRegistro','sincronizarDatosRegistro','pintarDocenteResponsable','actualizarDocenteResponsable'].map(n=>extract(n)).join('\n'),c);return {c,el};
}
test('DATOS uses responsive 3/2/1 columns, compact text identity and a hidden compatibility input',()=>{
 const panel=html.slice(html.indexOf('id="registroDatosPanel"'),html.indexOf('<main class="shell shell-work'));for(const id of ['selBim','selGrado','selSeccion','lblN','lblDocenteResponsable','inpDocente'])assert.match(panel,new RegExp('id="'+id+'"'));
 assert.match(panel,/<input type="hidden" id="inpDocente">/);assert.doesNotMatch(panel,/onchange="guardarMeta|grid-template-columns:1fr 1fr|contenteditable/);assert.match(html,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);assert.match(html,/@media \(max-width:600px\).*repeat\(2,minmax\(0,1fr\)\)/);assert.match(html,/@media \(max-width:360px\).*grid-template-columns:minmax\(0,1fr\)/);assert.match(html,/min-width:0/);
});
test('DATOS button is outside its panel and toggles hidden/aria without changing context or notes',()=>{
 assert.ok(html.indexOf('id="btnRegistroDatos"')<html.indexOf('id="registroDatosPanel"'));assert.match(html,/aria-controls="registroDatosPanel" aria-expanded="true" onclick="alternarDatosRegistro\(\)"/);
 const f=dataUI(),before=JSON.stringify([f.c.store,f.el('selBim').value,f.el('selGrado').value,f.el('selSeccion').value]);f.c.alternarDatosRegistro();assert.equal(f.el('registroDatosPanel').hidden,true);assert.equal(f.el('btnRegistroDatos').attrs['aria-expanded'],'false');f.c.alternarDatosRegistro();assert.equal(f.el('registroDatosPanel').hidden,false);assert.equal(f.el('btnRegistroDatos').attrs['aria-expanded'],'true');assert.equal(JSON.stringify([f.c.store,f.el('selBim').value,f.el('selGrado').value,f.el('selSeccion').value]),before);assert.equal(f.c.dirty,false);
});
test('valid context starts collapsed, explicit expansion survives refresh, missing selections or authorized roster reopen DATOS',()=>{
 const f=dataUI();f.c.sincronizarDatosRegistro();assert.equal(f.el('registroDatosPanel').hidden,true);f.c.alternarDatosRegistro();f.c.sincronizarDatosRegistro();assert.equal(f.el('registroDatosPanel').hidden,false);f.c.alternarDatosRegistro();f.el('selGrado').value='';f.c.sincronizarDatosRegistro();assert.equal(f.el('registroDatosPanel').hidden,false);f.el('selGrado').value='2';f.c.registroSoloLectura=()=>true;f.c.sincronizarDatosRegistro();assert.equal(f.el('registroDatosPanel').hidden,false);
});
for(const role of ['docente','admin'])test(role+' visible identity matches hidden official teacher across area refresh',()=>{
 const f=dataUI();f.c.getLoginSession=()=>({role,label:'Synthetic Teacher'});f.c.actualizarDocenteResponsable();const expected=role==='admin'?'Assigned Admin Teacher':'Synthetic Teacher';assert.equal(f.el('inpDocente').value,expected);assert.equal(f.el('lblDocenteResponsable').textContent,expected);assert.equal(f.el('inpDocente').readOnly,true);f.c.docenteAsignadoAdmin=()=> 'Next Assigned Teacher';f.c.getLoginSession=()=>({role,label:'Next Teacher'});f.c.actualizarDocenteResponsable();assert.equal(f.el('lblDocenteResponsable').textContent,f.el('inpDocente').value);
});
test('all academic, cloud, roster, storage and print functions remain byte-identical outside approved presentation hooks',()=>{
 const allowed=new Set(['actualizarDocenteResponsable','sincronizarEdicionRegistro','updateHdr','renderAvance']);for(const [,name]of old.matchAll(/^(?:async )?function (\w+)\(/gm))if(!allowed.has(name))assert.equal(extract(name),extract(name,old),name);
 for(const name of ['updateHdr','sincronizarEdicionRegistro'])assert.equal(extract(name).replace(/  if \(typeof sincronizarDatosRegistro === 'function'\) sincronizarDatosRegistro\(\);\n/g,''),extract(name,old));
 assert.equal(extract('actualizarDocenteResponsable').replace(/    pintarDocenteResponsable\(\);\n|  pintarDocenteResponsable\(\);\n/g,'').replace("inp.value = nombreDocenteTexto(previo);\n  inp.readOnly = true;","inp.value = nombreDocenteTexto(previo);\n  inp.readOnly = false;"),extract('actualizarDocenteResponsable',old));
 assert.equal(extract('renderAvance').replace('class="fin-wrap fin-scroll-body"','class="fin-wrap"').replaceAll('<th class="fin-nom">','<th>'),extract('renderAvance',old));
});
test('official teacher hidden value still reaches metadata, cloud body and actual print output',()=>{
 const source=read('tests/registro-academic-model.test.cjs'),ui=new Function('require','__dirname',source.split('\nfor(const level')[0]+'\nreturn ui;')(require,__dirname),f=ui('secundaria');f.el('inpDocente').style={};f.c.getLoginSession=()=>({role:'docente',label:'Synthetic Official Teacher'});f.c.nombreDocenteTexto=String;
 vm.runInContext(extract('pintarDocenteResponsable')+'\n'+extract('actualizarDocenteResponsable'),f.c);f.c.actualizarDocenteResponsable();assert.equal(f.el('lblDocenteResponsable').textContent,'Synthetic Official Teacher');
 f.c.store.meta[f.c.cloudClaveReg()]={docente:f.el('inpDocente').value};vm.runInContext(extract('metaRegistro'),f.c);assert.equal(f.c.metaRegistro().docente,'Synthetic Official Teacher');assert.match(extract('guardarMeta'),/docente: document.getElementById\('inpDocente'\).value.trim\(\)/);assert.match(extract('subirRegistroNube'),/docente: \(document.getElementById\('inpDocente'\) \|\| \{\}\).value/);
 f.grade(f.comps[0],15);f.c.setTimeout=()=>0;vm.runInContext(extract('prepararImpresion'),f.c);f.c.prepararImpresion();assert.match(f.el('printArea').innerHTML,/Synthetic Official Teacher/);
});
test('Promedios and Resumen have screen-only 60vh/dvh scroll viewports, with sticky whole thead and opaque background',()=>{
 assert.match(html,/id="finLista" class="fin-wrap fin-scroll-body"/);assert.match(extract('renderAvance'),/class="fin-wrap fin-scroll-body"/);assert.match(html,/\.fin-scroll-body \{ max-height:60vh; max-height:60dvh; overflow-x:auto; overflow-y:auto; max-width:100%; \}/);assert.match(html,/\.fin-scroll-body \.fin-grid thead \{ position:sticky; top:0; z-index:4; background:#0f172a; \}/);assert.match(html,/\.fin-scroll-body \.fin-grid thead th \{ position:static; \}/);
 assert.match(html,/\.fin-scroll-body \.fin-grid thead th.fin-nom \{ position:sticky; top:auto; left:0; z-index:5; \}/);assert.doesNotMatch(html,/\.fin-scroll-body[^\n]*(?:nth-child|top:\d+px|tbody[^\n]*height)/);
});
test('both secondary header rows stay in one sticky thead without altering transversal adapter',()=>{
 const source=read('registro-transversales.js'),previous=execFileSync('git',['show','321c72933a69830f1f731514513e21c240e1529c:registro-transversales.js'],{cwd:root,encoding:'utf8'});assert.equal(source.replace(/\r\n/g,'\n'),previous.replace(/\r\n/g,'\n'));assert.match(source,/thead.insertBefore\(group,thead.firstChild\)/);assert.match(source,/const header=thead.querySelectorAll\('tr'\)\[1\]/);assert.match(html,/\.fin-scroll-body \.fin-grid thead \{ position:sticky/);
});
test('Resumen keeps horizontal sticky names, all result columns and editable C conclusions; Calificar gets no vertical viewport',()=>{
 const render=extract('renderAvance');assert.match(render,/<th class="fin-nom">Estudiante/);assert.match(render,/<tr><th class="fin-nom">/);assert.match(render,/Promedio referencial<small style="display:block/);assert.match(render,/academic-conclusion/);assert.match(render,/IERegistroTransversales.summary\(box\)/);
 const start=html.indexOf('id="panelCalificar"'),panel=html.slice(start,html.indexOf('<!-- /panelCalificar -->',start));assert.doesNotMatch(panel,/fin-scroll-body/);
});
test('Promedios compact header has context and unchanged segmented mode in row one, informational toolbar in row two before viewport',()=>{
 const start=html.indexOf('id="panelFinales"'),panel=html.slice(start,html.indexOf('<!-- PANEL ASISTENCIA -->',start)),header=panel.slice(panel.indexOf('<header'),panel.indexOf('</header>')+9);
 assert.match(header,/<div class="fin-header-top">[\s\S]*fin-header-context[\s\S]*id="lblFinCtx"[\s\S]*class="mode-toggle"/);assert.match(header,/data-modo="letra" onclick="setModoCalif\('letra'\)"/);assert.match(header,/data-modo="num" class="on" onclick="setModoCalif\('num'\)"/);assert.match(header,/<div class="fin-header-toolbar" id="finResumen"><\/div>/);
 assert.match(panel,/<\/header>\s*<div id="finLista" class="fin-wrap fin-scroll-body">/);assert.doesNotMatch(panel,/space-y-3|Por alumno: si escribes/);for(const id of ['lblFinCtx','finResumen','finLista','registroTutorLink'])assert.equal((panel.match(new RegExp('id="'+id+'"','g'))||[]).length,1);
});
test('Promedios toolbar wraps with uniform gaps and nested counters participate in the same flex row without forced full width',()=>{
 assert.match(html,/\.fin-header-top \{ display:flex; flex-wrap:wrap; align-items:center; gap:6px 12px;/);assert.match(html,/\.fin-header-context \{ flex:1 1 240px; min-width:0;/);assert.match(html,/\.fin-header-top \.mode-toggle \{ flex:0 0 180px; max-width:100%; margin-left:auto;/);assert.match(html,/\.fin-header-toolbar \{ display:flex; flex-wrap:wrap; align-items:center; gap:4px 8px; margin-top:4px;/);assert.match(html,/\.fin-header-toolbar > div \{ display:contents; \}/);assert.match(html,/\.fin-header \{ margin-bottom:6px; \}/);
});
test('Promedios render keeps academic counters, mode explanation and every calculation identical after header relocation',()=>{
 assert.equal(extract('renderFinales'),extract('renderFinales',old));assert.match(extract('renderFinales'),/Promedio directo prevalece sobre evidencias/);assert.match(extract('renderFinales'),/Celdas /);for(const level of ['AD','A','B','C'])assert.match(extract('renderFinales'),new RegExp('>'+level+' '));
});
