const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
const integration=read('tests/registro-transversales-integracion.test.cjs');
function helper(source,name){const i=source.indexOf('function '+name+'(');return source.slice(i,source.indexOf('\n}',i)+2);}
const {ui,uploadUi,academicUi}=new Function('require','__dirname',integration.split('\ntest(')[0]+'\n'+helper(integration,'uploadUi')+'\n'+helper(integration,'academicUi')+'\nreturn {ui,uploadUi,academicUi};')(require,__dirname);
function evidence(s,n=8){const session={fecha:'2026-10-14',comp:'tic',capacidad:s.c.registroEvaluacion_().CAPS.tic[0]};return {schema:1,sessions:[session],grades:{[s.c.registroEvaluacion_().sessionKey(session)]:{[s.id]:{modo:'num',valor:n}}},directos:{}};}
function own(s){return s.load('math').aportes.find(a=>a.user==='math');}
function persist(s,e,extra={}){return s.route('savetransversalaporte','math',{area:'Matemática',version:own(s)?.version||0,evidencia:e,...extra});}
function summary(f){const root=f.el('summary64');f.api.summary(root);return root.children.at(-1)?.innerHTML;}
function set(f,comp,value){return f.api.setDirect(f.api.current(),f.s.id,comp,{modo:'letra',valor:value});}
function conclusion(f,comp,text){return f.api.setConclusion(f.api.current(),f.s.id,comp,text);}
test('Resumen exposes both columns and loading state before any transversal response or academic evidence',()=>{const f=academicUi();f.c.renderAvance();const box=f.el('avanceBox').children[0];assert.match(box.innerHTML,/COMPETENCIAS TRANSVERSALES — APORTE DEL ÁREA/);assert.match(box.innerHTML,/<th>TIC<\/th><th>Gestiona su aprendizaje<\/th>/);assert.match(box.innerHTML,/Cargando competencias transversales/);});
test('A late transversal load repaints the already open actual Resumen without switching tabs',async()=>{const f=academicUi();f.el('panelAvance').classList.contains=x=>x==='on';const root=f.el('avanceBox');root.querySelector=()=>root.children.find(x=>x.id==='registroTransResumen')||null;f.c.document.createElement=()=>({innerHTML:'',className:'',querySelectorAll:()=>[],replaceWith(next){const i=root.children.indexOf(this);root.children[i]=next}});f.c.renderAvance();let resolve;const request=f.c.IETransversales.request;f.c.IETransversales.request=(a,p)=>new Promise(r=>resolve=()=>r(request(a,p)));const pending=f.api.load();assert.match(root.children.at(-1).innerHTML,/Cargando/);resolve();await pending;assert.match(root.children.at(-1).innerHTML,/Sin aporte/);assert.doesNotMatch(root.children.at(-1).innerHTML,/Cargando/);assert.equal(root.children.filter(x=>x.id==='registroTransResumen').length,1);});
test('Summary refresh remains independent when academic local persistence prevents full repaint',async()=>{const f=ui();f.el('panelAvance').classList.contains=()=>true;f.c.guardarTodo=()=>false;await f.api.load();assert.match(f.el('avanceBox').children.at(-1).innerHTML,/COMPETENCIAS TRANSVERSALES/);assert.match(f.el('avanceBox').children.at(-1).innerHTML,/Sin aporte/);});
test('Late old-context response never replaces current-context summary',async()=>{const f=ui();f.el('panelAvance').classList.contains=()=>true;let resolve;const request=f.c.IETransversales.request;f.c.IETransversales.request=(a,p)=>new Promise(r=>resolve=()=>r(request(a,p)));const pending=f.api.load();f.c.areaActual='Comunicación';const before=summary(f);resolve();await pending;assert.equal(summary(f),before);assert.match(before,/Cargando/);});
for(const source of ['evidencias','directo'])test('Effective C from '+source+' renders a required conclusion for TIC',async()=>{const f=ui();if(source==='evidencias')persist(f.s,evidence(f.s));await f.api.load();if(source==='directo')set(f,'tic','C');const html=summary(f);assert.equal((html.match(/<textarea/g)||[]).length,1);assert.match(html,/data-trans-comp="tic"[^>]*required/);assert.match(html,/Obligatoria para C/);assert.equal(f.api.missingConclusions(),true);});
for(const level of ['AD','A','B'])test('Effective '+level+' requires no area conclusion',async()=>{const f=ui();await f.api.load();set(f,'tic',level);assert.doesNotMatch(summary(f),/<textarea|required/);assert.equal(f.api.missingConclusions(),false);});
test('TIC C with autonomy A requires only TIC, both C require independent textareas',async()=>{const f=ui();await f.api.load();set(f,'tic','C');set(f,'autonomia','A');assert.equal((summary(f).match(/<textarea/g)||[]).length,1);set(f,'autonomia','C');assert.equal((summary(f).match(/<textarea/g)||[]).length,2);conclusion(f,'tic','Synthetic TIC conclusion');assert.equal(f.api.missingConclusions(),true);conclusion(f,'autonomia','Synthetic autonomy conclusion');assert.equal(f.api.missingConclusions(),false);assert.notEqual(f.api.current().evidence.conclusiones[f.s.id].tic,f.api.current().evidence.conclusiones[f.s.id].autonomia);});
test('C to A and back preserves the teacher text but marks it current only for C',async()=>{const f=ui();await f.api.load();set(f,'tic','C');conclusion(f,'tic','Synthetic draft conclusion');set(f,'tic','A');assert.match(summary(f),/borrador \(no vigente\)/);assert.doesNotMatch(summary(f),/<textarea/);assert.equal(f.api.missingConclusions(),false);set(f,'tic','C');assert.match(summary(f),/Synthetic draft conclusion<\/textarea>/);assert.equal(f.api.missingConclusions(),false);});
test('C without conclusion blocks integral Nube Subir and leaves academic request unsent',async()=>{const f=ui();await f.api.load();const u=uploadUi(f);set(f,'tic','C');assert.equal(await f.c.subirRegistroNube(),false);assert.match(u.messages.at(-1),/Falta conclusión descriptiva.*Complétala en Resumen/);assert.ok(!u.order.includes('savereg'));assert.equal(f.calls.filter(c=>c.action==='savetransversalaporte').length,0);});
test('Both C with independent conclusions permit one transversal block and academic upload',async()=>{const f=ui();await f.api.load();const u=uploadUi(f);for(const c of ['tic','autonomia']){set(f,c,'C');conclusion(f,c,'Synthetic conclusion '+c);}assert.equal(await f.c.subirRegistroNube(),true);assert.equal(u.order.filter(x=>x==='savetransversalaporte').length,1);assert.ok(u.order.includes('savereg'));const saved=own(f.s).evidencia.conclusiones[f.s.id];assert.equal(saved.tic,'Synthetic conclusion tic');assert.equal(saved.autonomia,'Synthetic conclusion autonomia');assert.equal(f.calls.find(c=>c.action==='savetransversalaporte').envioIntegral,true);assert.doesNotMatch(JSON.stringify(f.upload.payload),/conclusiones|Synthetic conclusion/);});
test('Backend independently rejects integral C without conclusion atomically but allows incomplete draft',()=>{const f=ui(),e=evidence(f.s),writes=f.s.state.writes;assert.equal(persist(f.s,e,{envioIntegral:true}).ok,false);assert.equal(f.s.state.writes,writes);assert.equal(persist(f.s,e).ok,true);e.conclusiones={[f.s.id]:{tic:'Synthetic complete conclusion'}};assert.equal(persist(f.s,e,{envioIntegral:true}).ok,true);});
test('Old backend cannot silently discard new conclusions on integral upload',async()=>{const f=ui(),request=f.c.IETransversales.request;f.c.IETransversales.request=async(a,p)=>{const out=await request(a,p);delete out.soportaConclusiones;return out};await f.api.load();const u=uploadUi(f);set(f,'tic','A');assert.equal(conclusion(f,'tic','Synthetic'),false);assert.equal(await f.c.subirRegistroNube(),false);assert.ok(!u.order.includes('savereg'));assert.equal(f.el('registroTransAviso').hidden,false);});
test('Teacher conclusions reach Tutor/AIP area summaries without becoming the official consolidated conclusion',()=>{const f=ui(),e=evidence(f.s);e.conclusiones={[f.s.id]:{tic:'Synthetic teacher conclusion'}};persist(f.s,e);for(const user of ['math','pip','admin']){const data=f.s.load(user);assert.equal(data.resultados[f.s.id].tic.resumen.aportes[0].conclusion,'Synthetic teacher conclusion');assert.equal(data.resultados[f.s.id].tic.final,null);}assert.equal(f.s.final('math','C').ok,true);assert.equal(f.s.confirm('math','confirmtransversaltutor').ok,false);assert.equal(f.s.final('math','C',undefined,undefined,'Synthetic official conclusion').ok,true);f.s.confirm('math','confirmtransversaltutor');const out=f.s.confirm('pip','confirmtransversalaip');assert.equal(out.resultados[f.s.id].tic.final.conclusion,'Synthetic official conclusion');assert.equal(out.resultados[f.s.id].tic.listo,true);});
test('Non-C contributions retain historical teacher text but do not expose it as a current conclusion',()=>{const f=ui(),e=evidence(f.s,15);e.conclusiones={[f.s.id]:{tic:'Synthetic prior C text'}};persist(f.s,e);assert.equal(own(f.s).evidencia.conclusiones[f.s.id].tic,'Synthetic prior C text');assert.equal(f.s.load('pip').resultados[f.s.id].tic.resumen.aportes[0].conclusion,'');});
test('Conclusion edit and exact restore is no-op for dirty, rows, version and confirmations',async()=>{const f=ui(),e=evidence(f.s);e.conclusiones={[f.s.id]:{tic:'Synthetic Text A'}};persist(f.s,e);f.s.final('math','A');f.s.confirm('math','confirmtransversaltutor');f.s.confirm('pip','confirmtransversalaip');await f.api.load();const before=f.s.load('pip'),rows=f.s.tables.get('TransversalesAportes').rows.length;conclusion(f,'tic','Synthetic Text B');assert.equal(f.api.current().dirty,true);conclusion(f,'tic','Synthetic Text A');assert.equal(f.api.current().dirty,false);await f.api.save();assert.equal(f.s.tables.get('TransversalesAportes').rows.length,rows);assert.equal(f.s.load('pip').versionAportes,before.versionAportes);assert.equal(f.s.load('pip').resultados[f.s.id].tic.listo,true);});
test('Real conclusion change versions, invalidates both confirmations and retains append history',async()=>{const f=ui(),e=evidence(f.s);e.conclusiones={[f.s.id]:{tic:'Synthetic Text A'}};persist(f.s,e);f.s.final('math','A');f.s.confirm('math','confirmtransversaltutor');f.s.confirm('pip','confirmtransversalaip');await f.api.load();const before=f.s.load('pip'),version=f.api.current().version,rows=JSON.stringify(f.s.tables.get('TransversalesAportes').rows);conclusion(f,'tic','Synthetic Text B');assert.equal(await f.api.save(),true);const out=f.s.load('pip');assert.notEqual(out.versionAportes,before.versionAportes);assert.ok(f.api.current().version>version);assert.equal(out.resultados[f.s.id].tic.listo,false);assert.match(out.resultados[f.s.id].tic.estado,/Requiere nueva confirmación/);assert.equal(JSON.stringify(f.s.tables.get('TransversalesAportes').rows.slice(0,-1)),rows);});
test('Historical evidence without conclusions stays readable; older writes preserve saved teacher text',()=>{const f=ui(),e=evidence(f.s);persist(f.s,e);assert.deepEqual(clone(own(f.s).evidencia.conclusiones),{});e.conclusiones={[f.s.id]:{tic:'Synthetic retained text'}};persist(f.s,e);delete e.conclusiones;persist(f.s,e);assert.equal(own(f.s).evidencia.conclusiones[f.s.id].tic,'Synthetic retained text');e.conclusiones={};persist(f.s,e);assert.deepEqual(clone(own(f.s).evidencia.conclusiones),{});});
for(const [label,texts] of [['foreign',{'id:foreign':{tic:'Synthetic'}}],['comp',{'id:synthetic-a':{invented:'Synthetic'}}],['nonstring',{'id:synthetic-a':{tic:42}}],['long',{'id:synthetic-a':{tic:'x'.repeat(2001)}}],['array',[]]])test('Backend rejects conclusion '+label+' with no append',()=>{const f=ui(),e=evidence(f.s);e.conclusiones=texts;const writes=f.s.state.writes;assert.equal(persist(f.s,e).ok,false);assert.equal(f.s.state.writes,writes);});
test('Backend sanitizes control characters and CRLF and retains plain text safely',()=>{const f=ui(),e=evidence(f.s);e.conclusiones={[f.s.id]:{tic:' \u0000Synthetic\r\n conclusion\u0007 '}};assert.equal(persist(f.s,e).ok,true);assert.equal(own(f.s).evidencia.conclusiones[f.s.id].tic,'Synthetic\n conclusion');});
test('Conclusion textarea escapes markup rather than executing it',async()=>{const f=ui();await f.api.load();set(f,'tic','C');conclusion(f,'tic','<script>synthetic</script>');assert.match(summary(f),/&lt;script&gt;/);assert.doesNotMatch(summary(f),/<script>/);});
test('Conclusion draft edited during an in-flight save is retained dirty against the saved baseline',async()=>{const f=ui();await f.api.load();set(f,'tic','C');conclusion(f,'tic','Synthetic A');const request=f.c.IETransversales.request;let resolve;f.c.IETransversales.request=(a,p)=>new Promise(r=>resolve=()=>r(request(a,p)));const pending=f.api.save();conclusion(f,'tic','Synthetic B');resolve();await pending;assert.equal(f.api.current().evidence.conclusiones[f.s.id].tic,'Synthetic B');assert.equal(f.api.current().dirty,true);assert.equal(own(f.s).evidencia.conclusiones[f.s.id].tic,'Synthetic A');conclusion(f,'tic','Synthetic A');assert.equal(f.api.current().dirty,false);});
test('Primary receives no new transversal summary, setters or upload requirement',async()=>{const f=ui();f.c.nivel='primaria';assert.equal(summary(f),undefined);const u=uploadUi(f);assert.equal(await f.c.subirRegistroNube(),true);assert.deepEqual(u.order,['local','savereg']);});
test('Conclusions never enter academic/SIAGIE payload or general academic average',async()=>{const f=ui();await f.api.load();set(f,'tic','C');conclusion(f,'tic','Synthetic separate conclusion');assert.deepEqual(clone(f.c.store.concArea),{});assert.deepEqual(clone(f.c.store.grades),{});assert.deepEqual(clone(f.c.store.finales),{});assert.equal(f.c.competencias().length,1);assert.doesNotMatch(read('registro.html').slice(read('registro.html').indexOf('function informeSiagie('),read('registro.html').indexOf('\n}',read('registro.html').indexOf('function informeSiagie('))),/conclusiones|IERegistroTransversales/);});
for(const role of ['math','pip'])test('Actual '+role+' consolidation editor shows teacher conclusion without prefilling official conclusion',()=>{const f=ui(),e=evidence(f.s);e.conclusiones={[f.s.id]:{tic:'Synthetic source conclusion'}};persist(f.s,e);function create(tag){return {tagName:tag,style:{},children:[],textContent:'',value:'',setAttribute(){},appendChild(x){this.children.push(x)},replaceChildren(){this.children=[]},querySelectorAll(tag){return this.children.flatMap(c=>[...(c.tagName===tag?[c]:[]),...c.querySelectorAll(tag)])}}};const c=vm.createContext({window:null,document:{createElement:create},IERegistroEvaluacion:f.c.IERegistroEvaluacion});c.window=c;vm.runInContext(read('transversales-client.js'),c);const root=create('div');c.IETransversales.editor(root,clone(f.s.load(role)),f.s.ctx,true);assert.ok(root.querySelectorAll('p').some(p=>p.textContent==='Conclusión del docente: Synthetic source conclusion'));assert.ok(root.querySelectorAll('textarea').every(t=>t.value===''));});
test('Required conclusion textarea input handler and capture preserve pending text across a late summary repaint',async()=>{const f=ui();await f.api.load();set(f,'tic','C');const e=f.api.current(),field={value:'Synthetic pending textarea text',dataset:{transEntry:String(e.id),transId:f.s.id,transComp:'tic'}};f.c.document.querySelectorAll=sel=>sel==='.trans-conclusion'?[field]:[];f.api.capture();assert.equal(e.evidence.conclusiones[f.s.id].tic,field.value);assert.match(summary(f),/Synthetic pending textarea text<\/textarea>/);assert.equal(e.dirty,true);});
test('Unknown historical teacher identities are not exposed through conclusion maps',()=>{const f=ui(),e=evidence(f.s);e.conclusiones={[f.s.id]:{tic:'Synthetic valid conclusion'}};persist(f.s,e);const rows=f.s.tables.get('TransversalesAportes').rows,payload=JSON.parse(rows[1][8]);payload.conclusiones['id:foreign']={tic:'Synthetic unauthorized text'};rows[1][8]=JSON.stringify(payload);assert.doesNotMatch(JSON.stringify(f.s.load('pip').aportes),/Synthetic unauthorized text/);});
test('Conclusion change retains exact Letras/0-20 behavior and view switching never creates another conclusion version',async()=>{const f=ui();await f.api.load();set(f,'tic','C');conclusion(f,'tic','Synthetic saved conclusion');await f.api.save();const e=f.api.current(),before=f.s.load('pip').versionAportes;for(const mode of ['num','letra','num']){f.c.modoCalif=mode;const html=summary(f);assert.match(html,/Synthetic saved conclusion/);assert.doesNotMatch(html,/8 → C/);await f.api.save();}assert.equal(e.dirty,false);assert.equal(f.s.load('pip').versionAportes,before);});
