const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
const integ=read('tests/registro-transversales-integracion.test.cjs');
function helper(s,n){const i=s.indexOf('function '+n+'(');return s.slice(i,s.indexOf('\n}',i)+2);}
const {academicUi,extract}=new Function('require','__dirname',integ.split('\ntest(')[0]+'\n'+helper(integ,'academicUi')+'\nreturn {academicUi,extract};')(require,__dirname);
const backend=new Function('require','__dirname',read('tests/backend-write-auth.test.cjs').split('\nfor (const action')[0]+'\nreturn setup;')(require,__dirname);
const identity=new Function('require','__dirname',read('tests/registro-roster-identity.test.cjs').split('\ntest(')[0]+'\nreturn {fixture,extract};')(require,__dirname);
function ui(level='secundaria'){
 const f=academicUi(),c=f.c;c.nivel=level;c.areaActual='Matemática';c.identidadAlumno=String;c.cloudClaveReg=()=>[level,'I',2,'A','Matemática'].join('||');
 vm.runInContext(read('registro-academic-model.js'),c);const comps=c.IERegistroAcademico.catalog[level]['Matemática'];c.competencias=()=>comps;
 c.prefijoReg=()=>c.cloudClaveReg()+'||';c.tsDe=x=>x&&x.ts||0;c.guardarTodo=()=>true;c.dirty=false;c.studentKey=a=>typeof a==='object'?'id:'+a.idSiagie:String(a);c.store.concComp={};c.store.competenciasEstado={};
 c.loadStore=()=>{};c.fillComps=c.renderStudents=c.renderFinales=()=>{};
 for(const n of ['finalKey','sliceRegistroArea','metaRegistro','baselineAcademica','dirtyAcademico','setConclusionAcademica','setCompetenciaTrabajada','numeroExactoComp','promReferencialAlumno','validarConclusionesOficial','informeSiagie','renderAvance','renderFinales','upsertSesionCap','prepararVersionAcademica','mergeRegistroPayload'])vm.runInContext(extract(n),c);
 c.aliasesAula=()=>({});c.metaRegistro=()=>({});c.asisCtxKey=()=>[level,'I',2,'A'].join('||');c.mergeFechasAsistencia=()=>{};
 const id=c.studentKey(f.s.roster[0]);return {...f,c,comps,id,key:cp=>c.finalKey(cp,id),grade:(cp,n,origin='numero')=>{c.store.finales[c.finalKey(cp,id)]={nota20:n,nivel:c.numToLetter(n),origen:origin,ts:100};},conclusion:(cp,text)=>c.setConclusionAcademica(cp,id,text)};
}
for(const level of ['primaria','secundaria']){
 for(const [n,L,required] of [[18,'AD',false],[15,'A',false],[12,'B',false],[8,'C',true]])test(level+': effective '+L+' requires its own conclusion only for C',()=>{const f=ui(level);f.grade(f.comps[0],n);assert.equal(f.c.validarConclusionesOficial(f.c.ctxBase(),f.c.estudiantes(),[]).length,required?1:0);});
 test(level+': two Cs need two independent conclusions; concArea never satisfies them',()=>{const f=ui(level);f.grade(f.comps[0],8);f.grade(f.comps[1],9);f.c.store.concArea['old']={texto:'Old general conclusion'};assert.equal(f.c.validarConclusionesOficial({},f.c.estudiantes(),[]).length,2);f.conclusion(f.comps[0],'First competence');assert.equal(f.c.validarConclusionesOficial({},f.c.estudiantes(),[]).length,1);f.conclusion(f.comps[1],'Second competence');assert.equal(f.c.validarConclusionesOficial({},f.c.estudiantes(),[]).length,0);assert.equal(f.c.concCompAlumno(f.comps[0],f.id),'First competence');});
 test(level+': direct C wins over B evidence and requires its own conclusion',()=>{const f=ui(level);f.c.notaDesdeSesiones=()=>({nota:12,letra:'B'});f.grade(f.comps[0],8);assert.equal(f.c.notaCompAlumno(f.comps[0],f.id).src,'P');assert.equal(f.c.notaCompAlumno(f.comps[0],f.id).letra,'C');assert.ok(f.c.validarConclusionesOficial({},f.c.estudiantes(),[]).length);});
 test(level+': deactivation conserves every grade/session/direct/conclusion and reactivation restores C',()=>{const f=ui(level);f.grade(f.comps[0],8);f.conclusion(f.comps[0],'Conserved');f.c.upsertSesionCap(f.comps[0],'Capacity');f.c.store.grades['historical']={nota20:12};const old=clone({sessions:f.c.store.sessions,grades:f.c.store.grades,finales:f.c.store.finales,concComp:f.c.store.concComp});assert.equal(f.c.setCompetenciaTrabajada(f.comps[0],false),true);assert.equal(f.c.notaCompAlumno(f.comps[0],f.id).letra,'');assert.equal(f.c.validarConclusionesOficial({},f.c.estudiantes(),[]).length,0);assert.deepEqual(clone({sessions:f.c.store.sessions,grades:f.c.store.grades,finales:f.c.store.finales,concComp:f.c.store.concComp}),old);f.c.setCompetenciaTrabajada(f.comps[0],true);assert.equal(f.c.notaCompAlumno(f.comps[0],f.id).letra,'C');assert.equal(f.c.concCompAlumno(f.comps[0],f.id),'Conserved');});
 test(level+': cancel confirmation retains worked state and all data',()=>{const f=ui(level);f.grade(f.comps[0],8);f.c.confirm=()=>false;const old=JSON.stringify(f.c.store);assert.equal(f.c.setCompetenciaTrabajada(f.comps[0],false),false);assert.equal(f.c.competenciaTrabajada(f.comps[0]),true);assert.equal(JSON.stringify(f.c.store),old);});
 test(level+': active without result is pending; inactive blank is valid and not zero',()=>{const f=ui(level);assert.equal(f.c.informeSiagie().ok,false);f.comps.forEach(cp=>f.c.setCompetenciaTrabajada(cp,false));const info=f.c.informeSiagie();assert.equal(info.ok,true);assert.equal(info.faltanNota.length,0);assert.equal(info.faltanConc.length,0);assert.equal(Object.values(info.filas[0].letras).every(x=>x===''),true);});
 test(level+': C to A and back conserves and restores its conclusion draft',()=>{const f=ui(level);f.grade(f.comps[0],8);f.conclusion(f.comps[0],'Persistent draft');f.grade(f.comps[0],15);f.c.renderAvance();assert.match(f.el('avanceBox').innerHTML,/borrador/);assert.doesNotMatch(f.el('avanceBox').innerHTML,/<textarea/);f.grade(f.comps[0],8);f.c.renderAvance();assert.match(f.el('avanceBox').innerHTML,/<textarea[^>]*required/);assert.match(f.el('avanceBox').innerHTML,/Persistent draft/);});
 test(level+': worked true→false→true returns baseline without dirty',()=>{const f=ui(level);f.c.baselineAcademica();f.c.setCompetenciaTrabajada(f.comps[0],false);assert.equal(f.c.dirty,true);f.c.setCompetenciaTrabajada(f.comps[0],true);assert.equal(f.c.dirty,false);});
 test(level+': conclusion A→B→A returns exact baseline without dirty',()=>{const f=ui(level);f.conclusion(f.comps[0],'Text A');f.c.store.academicSync={};f.c.baselineAcademica();f.conclusion(f.comps[0],'Text B');assert.equal(f.c.dirty,true);f.conclusion(f.comps[0],'Text A');assert.equal(f.c.dirty,false);});
 test(level+': partial conclusions save locally, while integral area stays pending',()=>{const f=ui(level);f.grade(f.comps[0],8);assert.equal(f.conclusion(f.comps[0],'Partial draft'),true);assert.equal(f.c.informeSiagie().ok,false);assert.equal(f.c.sliceRegistroArea().concComp[f.key(f.comps[0])].texto,'Partial draft');});
 test(level+': inactive competence cannot add evidence or change conclusion',()=>{const f=ui(level);f.c.setCompetenciaTrabajada(f.comps[0],false);const snapshot=JSON.stringify(f.c.store);assert.equal(f.c.upsertSesionCap(f.comps[0],'New capacity'),false);assert.equal(f.conclusion(f.comps[0],'New conclusion'),false);assert.equal(JSON.stringify(f.c.store),snapshot);});
 test(level+': closed semester prohibits worked metadata and conclusion edits',()=>{const f=ui(level);f.c.bimCerradoDocente=()=>true;assert.equal(f.c.setCompetenciaTrabajada(f.comps[0],false),false);assert.equal(f.conclusion(f.comps[0],'Denied'),false);});
 test(level+': referential uses effective active results, no artificial exact numbers for letters',()=>{const f=ui(level);f.grade(f.comps[0],15,'letra');f.grade(f.comps[1],8);f.grade(f.comps[2],20);f.c.setCompetenciaTrabajada(f.comps[2],false);const r=f.c.promReferencialAlumno(f.id);assert.equal(r.n,2);assert.equal(r.exacto,false);assert.equal(r.letra,'B');f.c.modoCalif='num';f.c.renderAvance();assert.match(f.el('avanceBox').innerHTML,/Promedio referencial/);assert.doesNotMatch(f.el('avanceBox').innerHTML,/11.5 →/);});
 test(level+': no active results displays dash and never demands referential conclusion',()=>{const f=ui(level);f.comps.forEach(cp=>f.c.setCompetenciaTrabajada(cp,false));assert.equal(f.c.promReferencialAlumno(f.id).letra,'');f.c.renderAvance();assert.match(f.el('avanceBox').innerHTML,/<td>—<\/td>/);assert.equal(f.c.informeSiagie().ok,true);});
 test(level+': Resumen is a clean per-competence grid with independent textareas',()=>{const f=ui(level);f.grade(f.comps[0],8);f.grade(f.comps[1],9);f.c.upsertSesionCap(f.comps[0],'Hidden evidence capacity');f.conclusion(f.comps[0],'First');f.conclusion(f.comps[1],'Second');f.c.renderAvance();const html=f.el('avanceBox').innerHTML;assert.equal((html.match(/<textarea/g)||[]).length,2);assert.match(html,/First/);assert.match(html,/Second/);assert.doesNotMatch(html,/Hidden evidence capacity/);assert.match(html,/Promedio referencial.*no SIAGIE/);});
 for(const mode of ['letra','num'])test(level+': Promedios '+mode+' exposes removal only for actual direct grades',()=>{const f=ui(level);f.c.modoCalif=mode;f.c.renderFinales();assert.doesNotMatch(f.el('finLista').innerHTML,/Quitar directo/);f.grade(f.comps[0],15,'letra');f.c.renderFinales();assert.match(f.el('finLista').innerHTML,/Quitar directo/);assert.doesNotMatch(f.el('finLista').innerHTML,/value="15"/);f.c.setCompetenciaTrabajada(f.comps[0],false);f.c.renderFinales();assert.match(f.el('finLista').innerHTML,/No trabajada/);assert.doesNotMatch(f.el('finLista').innerHTML,/Quitar directo/);});
}
for(const level of ['primaria','secundaria'])test(level+': server saves and reads competence state and independent conclusions atomically',()=>{const s=backend(),ctx={nivel:level,bim:'I',grado:1,seccion:level==='primaria'?'Única':'A',area:'Matemática'},model=s.c.registroAcademico_(),cp=model.catalog[level][ctx.area][0],key=model.key(ctx,cp),id='id:synthetic',payload={concComp:{[key+'||'+id]:{texto:'Independent',ts:1}},competenciasEstado:{[key]:{trabajada:false,ts:1}}};const req={action:'savereg',token:level==='primaria'?s.primary:s.secondary,...ctx,bimestre:'I',modeloAcademico:1,version:0,payload};const result=s.post(req);assert.equal(result.ok,true,result.error);const read=s.post({action:'loadreg',nivel:level,token:req.token});assert.equal(read.soportaModeloAcademico,true);assert.equal(read.items[0].payload.concComp[key+'||'+id].texto,'Independent');assert.equal(read.items[0].payload.competenciasEstado[key].trabajada,false);assert.equal(s.state.held,false);});
function stored(){const s=backend(),model=s.c.registroAcademico_(),ctx={nivel:'primaria',bim:'I',grado:1,seccion:'Única',area:'Matemática'},cp=model.catalog.primaria[ctx.area][0],key=model.key(ctx,cp),req={action:'savereg',token:s.primary,...ctx,bimestre:'I',modeloAcademico:1,version:0,payload:{concComp:{[key+'||id:1']:{texto:'Baseline',ts:1}},competenciasEstado:{[key]:{trabajada:false,ts:1}}}},result=s.post(req);assert.equal(result.ok,true,result.error);return {s,model,ctx,cp,key,req,result};}
test('server stale version rejects overwrite and conserves stored notes/conclusions',()=>{const f=stored(),before=JSON.stringify(f.s.tables.get('RegistroNotas').rows),writes=f.s.state.writes;f.req.payload.concComp[f.key+'||id:1'].texto='Lost update';assert.equal(f.s.post(f.req).code,'CONFLICT');assert.equal(f.s.state.writes,writes);assert.equal(JSON.stringify(f.s.tables.get('RegistroNotas').rows),before);assert.equal(f.s.state.held,false);});
test('server identical canonical content with new timestamps produces no write or version',()=>{const f=stored();f.req.version=f.result.version;f.req.payload.concComp[f.key+'||id:1'].ts=999;const writes=f.s.state.writes,out=f.s.post(f.req);assert.equal(out.ok,true);assert.equal(out.unchanged,true);assert.equal(out.version,f.result.version);assert.equal(f.s.state.writes,writes);});
test('server real conclusion change persists and advances version; unversioned older client is rejected',()=>{const f=stored();f.req.version=f.result.version;f.req.payload.concComp[f.key+'||id:1'].texto='Changed';const out=f.s.post(f.req);assert.equal(out.ok,true);assert.ok(out.version>f.result.version);delete f.req.modeloAcademico;assert.equal(f.s.post(f.req).code,'CONFLICT');});
for(const kind of ['area','competence','student-context','bad-state','array','long-text','non-text'])test('server rejects invalid academic metadata: '+kind,()=>{const f=stored();f.req.version=f.result.version;const p=f.req.payload;if(kind==='area')p.competenciasEstado={['primaria||I||1||Única||Comunicación||'+f.cp]:{trabajada:false}};if(kind==='competence')p.competenciasEstado={[f.model.prefix(f.ctx)+'Foreign competence']:{trabajada:false}};if(kind==='student-context')p.concComp={['primaria||I||3||Única||Matemática||'+f.cp+'||id:1']:{texto:'Wrong context'}};if(kind==='bad-state')p.competenciasEstado[f.key].trabajada='false';if(kind==='array')p.concComp=[];if(kind==='long-text')p.concComp[f.key+'||id:1'].texto='x'.repeat(2001);if(kind==='non-text')p.concComp[f.key+'||id:1'].texto={secret:'not a string'};const writes=f.s.state.writes;assert.equal(f.s.post(f.req).ok,false);assert.equal(f.s.state.writes,writes);assert.equal(f.s.state.held,false);});
test('server validates existing permissions before academic state; forged role/area cannot grant EF',()=>{const f=stored();f.req.version=0;f.req.area='Educación Física';f.req.role='admin';assert.equal(f.s.post(f.req).ok,false);});
test('shared academic catalog/canonical code is identical in browser and Apps Script',()=>{const source=read('registro-academic-model.js').split("if(typeof window")[0];assert.ok(read('apps-script/Codigo.js').endsWith(source));});
test('legacy missing metadata means all worked, general conclusion remains historical only',()=>{const f=ui();f.c.store.concArea.old={texto:'Historical only'};f.comps.forEach(cp=>assert.equal(f.c.competenciaTrabajada(cp),true));assert.deepEqual(clone(f.c.store.concComp),{});assert.equal(f.c.concCompAlumno(f.comps[0],f.id),'');});
test('merge preserves newer local metadata/conclusions and restores newer cloud state on another device',()=>{const f=ui(),key=f.key(f.comps[0]),contextKey=key.slice(0,key.lastIndexOf('||'));f.c.store.concComp[key]={texto:'Local new',ts:20};f.c.store.competenciasEstado[contextKey]={trabajada:false,ts:20};f.c.mergeRegistroPayload({concComp:{[key]:{texto:'Cloud old',ts:10}},competenciasEstado:{[contextKey]:{trabajada:true,ts:10}}});assert.equal(f.c.store.concComp[key].texto,'Local new');assert.equal(f.c.competenciaTrabajada(f.comps[0]),false);f.c.mergeRegistroPayload({concComp:{[key]:{texto:'Cloud new',ts:30}},competenciasEstado:{[contextKey]:{trabajada:true,ts:30}}});assert.equal(f.c.store.concComp[key].texto,'Cloud new');assert.equal(f.c.competenciaTrabajada(f.comps[0]),true);const p=f.c.sliceRegistroArea(),g=ui();g.c.mergeRegistroPayload(p);assert.equal(g.c.concCompAlumno(g.comps[0],g.id),'Cloud new');});
for(const file of ['admin.html','registro.html'])for(const level of ['primaria','secundaria'])test(file+' '+level+': SIAGIE NL/CD stay paired; inactive/legacy/ref values are never exported',async()=>{
 const f=identity.fixture(),c=f.c,ctx={nivel:level,bim:'III',grado:4,seccion:'B',area:'Matemática'},al={idSiagie:'42',nombre:'Synthetic Student',grado:4,seccion:'B'};c.base=f.roster([al]);f.run("bdEstudiantes=base;nivel='"+level+"'");if(level==='primaria')c.base.primaria.estudiantes=[al];
 const comps=['Resuelve problemas de cantidad','Resuelve problemas de regularidad, equivalencia y cambio','Resuelve problemas de forma, movimiento y localización','Resuelve problemas de gestión de datos e incertidumbre'],pref=[level,'III',4,'B','Matemática'].join('||')+'||';const p={finales:{},concComp:{},concArea:{[pref+'id:42']:{texto:'Old area conclusion forbidden'}},competenciasEstado:{[pref+comps[3]]:{trabajada:false}}};comps.forEach((cp,i)=>{p.finales[pref+cp+'||id:42']={nivel:i===0?'A':'C'};p.concComp[pref+cp+'||id:42']={texto:['Never on A','Own competence two','Own competence three','Inactive old conclusion'][i]};});c.payload=p;f.run('store=payload');
 const ws={'!ref':'A1:K3',A3:{v:'42'},C3:{v:al.nombre}};for(const col of ['D','E','F','G','H','I','J','K'])ws[col+'3']={v:'STALE'};const wb={SheetNames:['MATE'],Sheets:{MATE:ws}};let exported=0;c.XLSX={read:()=>wb,write:()=>{exported++;return new Uint8Array()},utils:{decode_range:()=>({s:{r:0},e:{r:2}}),encode_cell:({r,c})=>String.fromCharCode(65+c)+(r+1)}};c.atob=atob;c.Blob=Blob;c.URL={createObjectURL:()=> 'synthetic'};c.document.createElement=()=>({click(){}});c.siagieTplMeta=null;c.areasDeNivel=()=>['Matemática'];c.ctxTpl=()=>ctx;c.compsDeArea=()=>comps;c.COMPS_SIAGIE={'Matemática':comps};c.areaDeHojaAdm=c.areaDeHojaSiagie=()=>({area:'Matemática',only:null});c.normNomAdm=c.normNomSiagie=c.IEStudentIdentity.normalizarNombre;c.fetchRegAula=async()=>[{area:'Matemática',payload:p}];c.IEStudents.loadRoster=async()=>c.base;c.fetchLecturaNube=async()=>({text:async()=>JSON.stringify({ok:true,b64:btoa('synthetic')})});c.CLOUD_API_URL='synthetic';c.informeSiagie=()=>({ok:true});c.getLoginSession=()=>({role:'admin'});c.IETransversales={request:async()=>({version:0,versionAportes:0,resultados:{}})};c.numToLetterAdm=n=>n>=14?'A':'C';c.promedioAdm=a=>a.length?a.reduce((x,y)=>x+y)/a.length:null;
 const names=file==='admin.html'?['letraDesdePayload','concDesdePayload','vaciarSiagieOficial']:['letraEnArea','concEnArea','rellenarSiagieExcel'];for(const n of names)f.run(identity.extract(file,n));await c[names[2]]();assert.equal(exported,1);assert.equal(ws.D3.v,'A');assert.equal(ws.E3,undefined);assert.equal(ws.F3.v,'C');assert.equal(ws.G3.v,'Own competence two');assert.equal(ws.H3.v,'C');assert.equal(ws.I3.v,'Own competence three');assert.equal(ws.J3,undefined);assert.equal(ws.K3,undefined);assert.doesNotMatch(JSON.stringify(ws),/Old area conclusion|Inactive old|STALE|Promedio referencial/);
});
for(const [action,expected] of [['backend-old','error'],['context-switch','error'],['fresh','ok']])test('academic baseline protected verification: '+action,async()=>{const f=ui();f.c.CLOUD_API_URL='synthetic';f.c.fetchLecturaNube=async()=>{if(action==='context-switch')f.c.cloudClaveReg=()=> 'other';return {text:async()=>JSON.stringify({ok:true,soportaModeloAcademico:action!=='backend-old',items:[]})}};if(expected==='error')await assert.rejects(f.c.prepararVersionAcademica());else{assert.equal(await f.c.prepararVersionAcademica(),true);assert.equal(f.c.baselineAcademica().version,0);}});

function uploadFixture(){const f=ui();f.comps.forEach(cp=>f.grade(cp,15));const c=f.c;c.CLOUD_API_URL='synthetic';c.getLoginSession=()=>({role:'admin',token:'synthetic-token'});c.retirarVerificacionNube=()=>{};const b=c.baselineAcademica();b.version=123;b.soportaModeloAcademico=true;const calls=[];c.fetch=async(url,opts)=>{calls.push(JSON.parse(opts.body));return {status:200,text:async()=>JSON.stringify({ok:true,version:124})}};vm.runInContext(extract('subirRegistroNube'),c);return {...f,c,calls};}
test('worked roundtrip identical to uploaded baseline does not POST or create a version',async()=>{const f=uploadFixture();f.c.setCompetenciaTrabajada(f.comps[0],false);f.c.setCompetenciaTrabajada(f.comps[0],true);assert.equal(await f.c.subirRegistroNube(),true);assert.equal(f.calls.length,0);assert.equal(f.c.baselineAcademica().version,123);});
test('conclusion roundtrip identical to uploaded baseline does not POST or create a version',async()=>{const f=uploadFixture();f.grade(f.comps[0],8);f.conclusion(f.comps[0],'Text A');const b=f.c.baselineAcademica();b.baseline=f.c.IERegistroAcademico.canonical(f.c.sliceRegistroArea());f.conclusion(f.comps[0],'Text B');f.conclusion(f.comps[0],'Text A');assert.equal(await f.c.subirRegistroNube(),true);assert.equal(f.calls.length,0);});
test('real worked change sends version and preserved original grades, without rewriting another context',async()=>{const f=uploadFixture();f.c.store.finales['primaria||II||6||Única||Comunicación||Other||id:9']={nota20:20};f.c.setCompetenciaTrabajada(f.comps[0],false);assert.equal(await f.c.subirRegistroNube(),true);assert.equal(f.calls.length,1);const body=f.calls[0];assert.equal(body.version,123);assert.equal(body.modeloAcademico,1);assert.equal(Object.keys(body.payload.competenciasEstado).length,1);assert.equal(body.payload.finales[f.key(f.comps[0])].nota20,15);assert.equal(body.payload.finales['primaria||II||6||Única||Comunicación||Other||id:9'],undefined);assert.equal(f.c.baselineAcademica().version,124);});
test('partial academic area blocks final upload but leaves its local draft intact',async()=>{const f=uploadFixture();delete f.c.store.finales[f.key(f.comps[0])];const old=JSON.stringify(f.c.store);assert.equal(await f.c.subirRegistroNube(),false);assert.equal(f.calls.length,0);assert.equal(JSON.stringify(f.c.store),old);});
test('new edits during savereg stay local and pending, never announce current area as complete',async()=>{const f=uploadFixture();f.c.setCompetenciaTrabajada(f.comps[3],false);f.c.fetch=async()=>{f.conclusion(f.comps[0],'Later change');return {status:200,text:async()=>JSON.stringify({ok:true,version:124})}};assert.equal(await f.c.subirRegistroNube(),false);assert.match(f.el('toast').textContent,/cambios locales posteriores/);assert.equal(f.c.concCompAlumno(f.comps[0],f.id),'Later change');assert.equal(f.c.dirty,true);});
test('server cell-size rejection preserves previous persisted record and releases the lock',()=>{const f=stored();f.req.version=f.result.version;f.req.payload.concArea={big:{texto:'x'.repeat(50000)}};const old=JSON.stringify(f.s.tables.get('RegistroNotas').rows),writes=f.s.state.writes;const out=f.s.post(f.req);assert.equal(out.ok,false);assert.match(out.error,/límite seguro/);assert.equal(f.s.state.writes,writes);assert.equal(JSON.stringify(f.s.tables.get('RegistroNotas').rows),old);assert.equal(f.s.state.held,false);});
test('student alias metadata remains canonical to preserve historical name-key reading on other devices',()=>{const s=backend().c.registroAcademico_();assert.notEqual(s.canonical({meta:{studentAliases:{'id:1':['Old name']}}}),s.canonical({meta:{studentAliases:{'id:1':['Old name','Corrected name']}}}));});
test('original letter evidence never yields a fabricated exact numeric Resumen/reference value',()=>{const f=ui();f.c.upsertSesionCap(f.comps[0],'Synthetic letter capacity');const c=f.c.ctxBase(),key=[c.nivel,c.bim,c.grado,c.seccion,c.area,f.comps[0],'Synthetic letter capacity','2026-10-14',f.id].join('||');f.c.store.grades[key]={nota20:15,nivel:'A',origen:'letra'};f.c.modoCalif='num';f.c.renderAvance();assert.equal(f.c.numeroExactoComp(f.comps[0],f.id),false);assert.doesNotMatch(f.el('avanceBox').innerHTML,/>15 →/);});

test('removing actual academic direct restores evidence and preserves its conclusion; missing direct is a no-op',()=>{const f=ui(),cp=f.comps[0];f.grade(cp,8);f.conclusion(cp,'Historical conclusion');f.c.notaDesdeSesiones=()=>({nota:12,letra:'B'});f.c.store.academicSync={};f.c.baselineAcademica();const button={dataset:{quitarDirecto:encodeURIComponent(cp),alumno:encodeURIComponent(f.id)}};f.el('finLista').querySelectorAll=sel=>sel==='[data-quitar-directo]'?[button]:[];f.c.renderFinales();button.onclick();assert.equal(f.c.notaCompAlumno(cp,f.id).letra,'B');assert.equal(f.c.concCompAlumno(cp,f.id),'Historical conclusion');assert.equal(f.c.dirty,true);const state=JSON.stringify(f.c.store);button.onclick();assert.equal(JSON.stringify(f.c.store),state);});
test('both level catalogs exclude TIC/autonomy from academic worked metadata',()=>{const f=ui(),core=f.c.IERegistroAcademico;for(const level of ['primaria','secundaria'])for(const area of Object.values(core.catalog[level]))assert.ok(area.every(cp=>!f.c.esCompetenciaTransversal(cp)));});
test('EF specialist can persist competence state but ordinary primary teacher cannot grant themselves EF',()=>{const p=read('tests/primary-area-assignments.test.cjs'),setup=new Function('require','__dirname',p.split('\nfor(const action')[0]+'\nreturn backend;')(require,__dirname),s=setup(),cp=s.c.registroAcademico_().catalog.primaria['Educación Física'][0],key='primaria||I||6||Única||Educación Física||'+cp,extra={modeloAcademico:1,version:0,payload:{competenciasEstado:{[key]:{trabajada:false}},concComp:{[key+'||id:synthetic']:{texto:'Own EF conclusion'}}}};assert.equal(s.req('savereg','test-primary',6,'Educación Física',extra).ok,false);assert.equal(s.req('savereg','synthetic-ef',6,'Educación Física',extra).ok,true);});
test('unversioned new metadata cannot silently bypass optimistic concurrency',()=>{const f=stored();f.req.version=f.result.version;delete f.req.modeloAcademico;const before=f.s.state.writes;assert.equal(f.s.post(f.req).code,'CONFLICT');assert.equal(f.s.state.writes,before);});
test('academic download from another context/token is discarded and cannot replace the active baseline',async()=>{const f=ui();f.c.CLOUD_API_URL='synthetic';f.c.fetchLecturaNube=async()=>{f.c.areaActual='Comunicación';return {text:async()=>JSON.stringify({ok:true,soportaModeloAcademico:true,items:[{clave:f.c.cloudClaveReg(),ts:999,payload:{concComp:{wrong:{texto:'Late response'}}}}]})}};vm.runInContext(extract('bajarRegistroNube'),f.c);const old=JSON.stringify(f.c.store);assert.equal(await f.c.bajarRegistroNube(),false);assert.equal(JSON.stringify(f.c.store),old);assert.match(f.el('toast').textContent,/contexto o la sesión cambió/);});

test('missing academic dependency never falls back to an unversioned official upload',async()=>{const f=uploadFixture();f.c.IERegistroAcademico=undefined;assert.equal(await f.c.subirRegistroNube(),false);assert.equal(f.calls.length,0);assert.match(f.el('toast').textContent,/No se cargó el modelo académico/);});

for(const level of ['primaria','secundaria'])test(level+': official print summary includes own C conclusion and inactive label, never historical area conclusion',()=>{const f=ui(level);f.c.setTimeout=()=>0;f.el('inpDocente').value='Synthetic Teacher';f.grade(f.comps[0],8);f.conclusion(f.comps[0],'Own printed competence conclusion');f.c.store.concArea.old={texto:'Forbidden general area conclusion'};f.c.setCompetenciaTrabajada(f.comps[1],false);vm.runInContext(extract('prepararImpresion'),f.c);f.c.prepararImpresion();const html=f.el('printArea').innerHTML;assert.match(html,/Resultados bimestrales por competencia/);assert.match(html,/Own printed competence conclusion/);assert.match(html,/No trabajada este bimestre/);assert.doesNotMatch(html,/Forbidden general area conclusion/);});
