const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),clone=x=>JSON.parse(JSON.stringify(x)),s=read('tests/transversales.test.cjs');
const {fixture,client}=new Function('require','__dirname',s.split('\ntest(')[0]+'\nreturn {fixture,client};')(require,__dirname);
const dom=new Function(s.slice(s.indexOf('function dom(){'),s.indexOf("test('real evidence grid"))+'\nreturn dom;')();
function grid(role='admin',C=false){const server=fixture();server.aporte('math',C?'C':15);if(C){const a=server.load('math').aportes[0],e=clone(a.evidencia);e.conclusiones={[server.id]:{tic:'Teacher C input',autonomia:'Independent autonomy input'}};assert.equal(server.route('savetransversalaporte','math',{area:'Matemática',version:a.version,evidencia:e}).ok,true);}const f=client(role),el=dom();f.c.document.createElement=el;f.run(read('transversales-client.js'));const box=el('div'),data=clone(server.load(role==='docente'?'math':role));const active=f.c.window.IETransversales.editor(box,data,server.ctx,true);return {server,f,box,data,active};}
test('final editor grid contains one row per student and separate TIC/autonomy/state columns',()=>{const f=grid(),table=f.box.querySelectorAll('table')[0];assert.ok(table);assert.equal(f.box.querySelectorAll('article').length,0);const rows=table.querySelectorAll('tbody')[0].querySelectorAll('tr');assert.equal(rows.length,f.data.estudiantes.length);const headers=table.querySelectorAll('thead')[0].querySelectorAll('th').map(e=>e.textContent);assert.deepEqual(headers,['N°','Estudiante','TIC','Gestiona su aprendizaje','Estado']);assert.equal(rows[0].querySelectorAll('details').filter(e=>e.className==='trans-detail').length,2);});
test('grid details are collapsed by default, keyboard accessible, with compact received/expected and alerts',()=>{const f=grid();const cells=f.box.querySelectorAll('details').filter(e=>e.className==='trans-detail');assert.equal(cells.length,2);cells.forEach(cell=>{assert.ok(!cell.open);const summary=cell.querySelectorAll('summary')[0];assert.match(summary.textContent,/A · 1\/3 aportes · ⚠/);assert.ok(!summary.disabled);});});
test('expanded detail contains areas/teacher/effective source/distribution/missing/suggestion without fabricated numbers',()=>{const f=grid(),cell=f.box.querySelectorAll('details').find(e=>e.className==='trans-detail'),strings=[...cell.querySelectorAll('p'),...cell.querySelectorAll('strong')].map(e=>e.textContent).join('\n');assert.match(strings,/Matemática · Synthetic Math/);assert.match(strings,/evidencias/);assert.match(strings,/AD: 0 · A: 1/);assert.match(strings,/Faltan:/);assert.match(strings,/Sugerencia del sistema/);assert.match(strings,/Requiere revisión colegiada/);});
test('teacher C conclusions are visible inside each detail but do not prefill official final conclusions',()=>{const f=grid('admin',true),cells=f.box.querySelectorAll('details').filter(e=>e.className==='trans-detail');assert.match(cells[0].querySelectorAll('p').map(e=>e.textContent).join('\n'),/Conclusión del docente: Teacher C input/);assert.match(cells[1].querySelectorAll('p').map(e=>e.textContent).join('\n'),/Independent autonomy input/);f.box.querySelectorAll('textarea').forEach(e=>assert.equal(e.value,''));});
for(const role of ['admin','docente','pip'])test(role+': grid preserves final/confirmation capabilities',()=>{if(role==='pip'){assert.equal(fixture().load('pip').ok,false);return;}const f=grid(role);const buttons=f.box.querySelectorAll('button').map(e=>e.textContent);if(role==='admin'){assert.deepEqual(buttons,[]);f.box.querySelectorAll('textarea').forEach(e=>assert.equal(e.disabled,true));f.box.querySelectorAll('select').slice(1).forEach(e=>assert.equal(e.disabled,true));}else{assert.ok(buttons.includes('Guardar decisión del Tutor'));assert.ok(!buttons.includes('Registrar revisión con Tutor'));assert.ok(buttons.includes('ENVIAR AL REGISTRO OFICIAL'));assert.ok(!buttons.includes('AIP confirma'));}assert.equal(f.active.dirty(),false);});
test('mobile grid retains horizontal scroll, sticky student, minimum targets and readable detail',()=>{const html=read('transversales.html');assert.match(html,/overflow-x:auto/);assert.match(html,/position:sticky;left:0/);assert.match(html,/min-width:170px/);assert.match(html,/min-height:44px/);assert.match(html,/@media\(max-width:640px\)/);assert.match(html,/trans-detail\[open\]/);});
test('presentation mode changes never mutate final decisions or confirm/version state',()=>{const f=grid('admin');const old=JSON.stringify(f.data),mode=f.box.querySelectorAll('select')[0];mode.value='num';mode.onchange();mode.value='letra';mode.onchange();assert.equal(f.active.dirty(),false);assert.equal(JSON.stringify(f.data),old);});
