const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),clone=x=>JSON.parse(JSON.stringify(x));
const fixture=new Function('require','__dirname',read('tests/transversales.test.cjs').split('\ntest(')[0]+'\nreturn fixture;')(require,__dirname);
function review(s){return s.confirm('admin','revisartransversal');}
function process(s){return s.confirm('admin','procesartransversales');}
function approved(){const s=fixture();assert.equal(s.final('admin','A').ok,true);assert.equal(review(s).ok,true);assert.equal(process(s).ok,true);return s;}
test('policy is centralized in institutional PERIODOS.anio, not browser date or payload year',()=>{const s=fixture();assert.equal(s.load('admin').politica.anio,2026);assert.equal(s.load('admin').politica.aportesObligatorios,false);s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:2027,bimestres:{I:'abierto'}});const out=s.route('loadtransversales','admin',{anio:2026});assert.equal(out.politica.aportesObligatorios,true);});
test('tutor and non-tutor can contribute both competences only through their actual assigned areas',()=>{const s=fixture();assert.equal(s.aporte('math','A').ok,true);assert.equal(s.aporte('communication','B').ok,true);assert.equal(s.load('admin').aportes.length,2);assert.equal(s.route('savetransversalaporte','communication',{area:'Matemática',version:0,evidencia:{schema:1,sessions:[],grades:{}}}).ok,false);});
test('optional missing contribution and unassigned teacher are distinct; missing optional contributions alone never alert',()=>{const s=fixture();s.aporte('math','A');s.c.registroAcademico_=()=>({catalog:{secundaria:{'Matemática':[],'Comunicación':[],'Educación Física':[]}}});const r=s.load('admin').resultados[s.id].tic.resumen;assert.equal(r.alerta,false);assert.equal(r.sugerencia,'A');assert.deepEqual(clone(r.sinAporte),['Comunicación','Educación Física']);assert.deepEqual(clone(r.sinDocente),[]);});
test('configuration inconsistency has a separate alert and never invents a C/zero for no contribution',()=>{const s=fixture(),r=s.load('admin').resultados[s.id].tic.resumen;assert.equal(r.recibidos,0);assert.equal(r.sugerencia,null);assert.ok(r.sinDocente.length>0);assert.equal(r.conteo.C,0);assert.equal(r.conteo.AD,0);});
for(const user of ['math','communication','pip','auxiliar'])test(user+' cannot decide, review or process as Admin even with forged role',()=>{const s=fixture();for(const action of ['savetransversalfinal','revisartransversal','procesartransversales']){const out=s.route(action,user,{role:'admin',revisadoConTutor:true,version:0,versionAportes:s.load('admin').versionAportes,finales:{}});assert.equal(out.ok,false);}if(user==='pip')assert.equal(s.route('confirmtransversalaip',user).ok,false);});
test('tutor reads assigned aula only and cannot confirm using obsolete technical actions',()=>{const s=fixture();assert.equal(s.load('math').ok,true);assert.equal(s.route('loadtransversales','math',{grado:2,seccion:'B'}).ok,false);assert.equal(s.route('confirmtransversaltutor','math').ok,false);});
test('Admin can decide with zero contributions, with explicit justification and independent final conclusion',()=>{const s=fixture();assert.equal(s.final('admin','A','').ok,false);assert.equal(s.final('admin','C','Pedagogical review',undefined,'Independent final conclusion').ok,true);const out=s.load('admin');assert.equal(out.resultados[s.id].tic.final.conclusion,'Independent final conclusion');assert.equal(out.exportable,false);});
test('process requires exactly one assigned tutor and explicit reviewed flag',()=>{const s=fixture();s.final('admin','A');assert.equal(process(s).ok,false);const data=s.load('admin');assert.equal(s.route('revisartransversal','admin',{version:data.version,versionAportes:data.versionAportes}).ok,false);s.docs[1].tutorAulas=[];s.tables.get('DocentesAcceso').rows[1][2]=JSON.stringify(s.docs);s.cacheEntries.clear();assert.equal(review(s).ok,false);assert.equal(process(s).ok,false);});
for(const missing of ['tic','autonomia','conclusion'])test('processing rejects incomplete '+missing+' without snapshot',()=>{const s=fixture();if(missing==='conclusion')s.final('admin','C','Reasoned decision');else{const data=s.load('admin');s.route('savetransversalfinal','admin',{version:0,versionAportes:data.versionAportes,finales:{[s.id]:{[missing==='tic'?'autonomia':'tic']:{modo:'letra',valor:'A',justificacion:'Reviewed decision'}}}});}review(s);assert.equal(process(s).ok,false);assert.equal(s.tables.has('TransversalesProcesado'),false);});
test('valid processing creates auditable approved snapshot independent of living contributions',()=>{const s=approved(),out=s.load('admin'),snap=out.procesado;assert.equal(out.exportable,true);assert.equal(snap.schema,2);assert.equal(snap.anio,2026);assert.equal(snap.admin,'admin');assert.equal(snap.revision.admin,'admin');assert.equal(snap.revision.tutor.user,'math');assert.equal(snap.versionAportes,out.versionAportes);assert.ok(snap.ts>0);assert.equal(snap.finales[s.id].tic.nivel,'A');});
test('later contribution keeps snapshot byte-identical, marks obsolete and prevents official export',()=>{const s=approved(),rows=JSON.stringify(s.tables.get('TransversalesProcesado').rows);s.aporte('communication','B');const view=s.load('admin'),out=s.route('loadtransversalexport','admin');assert.equal(view.procesado.finales[s.id].tic.nivel,'A');assert.equal(out.exportable,false);assert.equal(out.resultados[s.id].tic.final,null);assert.deepEqual(clone(out.aportes),[]);assert.equal(JSON.stringify(s.tables.get('TransversalesProcesado').rows),rows);assert.equal(process(s).ok,false);s.final('admin','B');review(s);assert.equal(process(s).ok,true);assert.ok(s.load('admin').versionProcesado>view.versionProcesado);});
test('official export exposes only processed valid final C and its approved independent text',()=>{const s=fixture();s.aporte('math','C');s.final('admin','C','Reviewed independently',undefined,'Approved final C');review(s);process(s);const out=s.route('loadtransversalexport','admin');assert.equal(out.resultados[s.id].tic.final.conclusion,'Approved final C');assert.equal(out.resultados[s.id].tic.listo,true);assert.deepEqual(clone(out.aportes),[]);assert.equal(out.resultados[s.id].tic.resumen,undefined);});
test('historical Tutor/AIP confirmations remain readable but never produce Admin processed status',()=>{const s=fixture(),d=s.load('admin');const old={modo:'letra',valor:'A',nivel:'A',versionAportes:d.versionAportes,tutor:{user:'math'},aip:{user:'pip'}};s.c.transversalAppend_('TransversalesConsolidado',['secundaria||I||2||A','I',2,'A',d.versionAportes,100,JSON.stringify({[s.id]:{tic:old,autonomia:old}})]);const out=s.load('admin');assert.equal(out.resultados[s.id].tic.final.tutor.user,'math');assert.equal(out.exportable,false);assert.equal(s.route('loadtransversalexport','admin').resultados[s.id].tic.final,null);});
test('review audit resets after actual final edit and optimistic conflicts remain atomic',()=>{const s=approved(),before=s.load('admin');s.final('admin','B');assert.equal(s.load('admin').revisado,null);const writes=s.state.writes;assert.equal(s.confirm('admin','procesartransversales',before).code,'CONFLICT');assert.equal(s.state.writes,writes);});
test('closed bimestre keeps approved read-only snapshot and refuses all new processing actions',()=>{const s=approved();s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:2026,bimestres:{I:'cerrado'}});for(const action of ['savetransversalfinal','revisartransversal','procesartransversales'])assert.equal(s.route(action,'admin').code,'PERIOD');assert.equal(s.load('admin').exportable,true);});
test('2027 policy requires assigned contributions before processing and invalidates 2026 snapshot',()=>{const s=approved();s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:2027,bimestres:{I:'abierto'}});assert.equal(s.load('admin').exportable,false);s.final('admin','A');review(s);assert.equal(process(s).ok,false);['math','communication','ef'].forEach(u=>s.aporte(u,'A'));s.final('admin','A');review(s);assert.equal(process(s).ok,true);});
test('conclusion suggestion copies editable text only; personalized choice and readonly preserve text',()=>{const c=vm.createContext({window:{}});vm.runInContext(read('conclusion-suggestions.js'),c);const api=c.window.IEConclusionSuggestions;assert.equal(api.suggestions('TIC').length,3);assert.match(api.html('Gestiona su aprendizaje'),/Escribir una conclusión personalizada/);assert.match(api.html('Resuelve problemas de cantidad'),/Resuelve problemas de cantidad/);});
test('static integration: single summary table, compact worked checkbox, Admin entry and new worker resources',()=>{const reg=read('registro.html'),adapter=read('registro-transversales.js'),admin=read('admin.html'),sw=read('sw.js');assert.match(reg,/width:17px;height:17px;min-height:17px/);assert.doesNotMatch(reg,/>Competencia trabajada<\/label>/);assert.match(adapter,/data-trans-summary/);assert.doesNotMatch(adapter.slice(adapter.indexOf('function summary('),adapter.indexOf('async function save(')),/<table|createElement\('section'\)/);assert.match(admin,/Registro General/);assert.match(admin,/href="transversales.html"/);assert.match(sw,/'v14'/);assert.match(sw,/'\.\/conclusion-suggestions.js'/);});
function academic(s){const cp=s.c.registroAcademico_().catalog.secundaria['Matemática'],finales=Object.fromEntries(cp.map(c=>['secundaria||I||2||A||Matemática||'+c+'||'+s.id,{nivel:'A',nota20:15,origen:'numero'}]));return {action:'savereg',token:s.token('math'),nivel:'secundaria',bimestre:'I',grado:2,seccion:'A',area:'Matemática',modeloAcademico:1,envioIntegral:true,version:0,payload:{finales}};}
for(const flag of [true,false,undefined])test('2026 server accepts academics without optional transversals; envioIntegral='+flag,()=>{const s=fixture(),req=academic(s);if(flag===undefined)delete req.envioIntegral;else req.envioIntegral=flag;assert.equal(s.post(req).ok,true);assert.equal(s.tables.has('TransversalesAportes'),false);});
test('2026 incomplete transversal C is a pending draft, not an academic blocker or automatic vote',()=>{const s=fixture(),core=s.c.registroEvaluacion_(),session={comp:'tic',fecha:'2026-10-14',capacidad:core.CAPS.tic[0]},e={schema:1,sessions:[session],grades:{[core.sessionKey(session)]:{[s.id]:{modo:'letra',valor:'C'}}}};assert.equal(s.route('savetransversalaporte','math',{area:'Matemática',version:0,evidencia:e}).ok,true);assert.equal(s.load('admin').resultados[s.id].tic.resumen.recibidos,0);assert.deepEqual(clone(s.load('admin').resultados[s.id].tic.resumen.pendientes),['Matemática']);assert.equal(s.post(academic(s)).ok,true);});
for(const flag of [true,false,undefined])test('2027 server rejects bypassed missing transversals; forged envioIntegral='+flag,()=>{const s=fixture();s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:2027,bimestres:{I:'abierto'}});const req=academic(s),before=s.tables.get('RegistroNotas').rows.length;req.anio=2026;req.role='admin';if(flag===undefined)delete req.envioIntegral;else req.envioIntegral=flag;const out=s.post(req);assert.equal(out.ok,false);assert.match(out.error,/requiere aportes transversales/);assert.equal(s.tables.get('RegistroNotas').rows.length,before);s.aporte('math','A');assert.equal(s.post(req).ok,true);});

test('existing C pending conclusion is not missing, not a complete vote or optional critical alert, and UI shows one condition',()=>{
 const s=fixture();s.c.registroAcademico_=()=>({catalog:{secundaria:{'Matemática':[],'Comunicación':[],'Educación Física':[]}}});
 const core=s.c.registroEvaluacion_(),session={comp:'tic',fecha:'2026-10-14',capacidad:core.CAPS.tic[0]},e={schema:1,sessions:[session],grades:{[core.sessionKey(session)]:{[s.id]:{modo:'letra',valor:'C'}}}};
 assert.equal(s.route('savetransversalaporte','math',{area:'Matemática',version:0,evidencia:e}).ok,true);
 const data=s.load('admin'),r=data.resultados[s.id].tic.resumen;assert.deepEqual(clone(r.pendientes),['Matemática']);assert.ok(!r.sinAporte.includes('Matemática'));assert.equal(r.conteo.C,0);assert.equal(r.recibidos,0);assert.equal(r.alerta,false);
 const source=read('tests/transversales.test.cjs'),client=new Function('require','__dirname',source.split('\ntest(')[0]+'\nreturn client;')(require,__dirname),dom=new Function(source.slice(source.indexOf('function dom(){'),source.indexOf("test('real evidence grid"))+'\nreturn dom;')(),f=client('admin'),el=dom();
 f.c.document.createElement=el;f.run(read('transversales-client.js'));const box=el('div');f.c.window.IETransversales.editor(box,clone(data),s.ctx,true);
 const tic=box.querySelectorAll('details').find(d=>d.className==='trans-detail'),messages=tic.querySelectorAll('p').map(p=>p.textContent);assert.equal(messages.filter(t=>t==='Matemática · Aporte C pendiente de conclusión').length,1);assert.ok(!messages.some(t=>t.startsWith('Matemática · ')&&t.endsWith('Sin aporte')));
});

test('2027 processing still rejects C pending conclusion after separating it from missing contributions',()=>{
 const s=fixture();s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:2027,bimestres:{I:'abierto'}});['math','communication','ef'].forEach(u=>assert.equal(s.aporte(u,'A').ok,true));
 const own=s.load('math').aportes.find(a=>a.user==='math'),e=clone(own.evidencia);const key=Object.keys(e.grades)[0];e.grades[key][s.id]={modo:'letra',valor:'C'};
 assert.equal(s.route('savetransversalaporte','math',{area:'Matemática',version:own.version,evidencia:e}).ok,true);const r=s.load('admin').resultados[s.id].tic.resumen;assert.ok(r.pendientes.includes('Matemática'));assert.ok(!r.sinAporte.includes('Matemática'));assert.equal(r.alerta,true);
 assert.equal(s.final('admin','A').ok,true);assert.equal(review(s).ok,true);assert.equal(process(s).ok,false);assert.equal(s.tables.has('TransversalesProcesado'),false);
});
test('changing Tutor invalidates review and processed snapshot without rewriting historical bytes',()=>{const s=approved(),old=JSON.stringify(s.tables.get('TransversalesProcesado').rows);s.docs[1].tutorAulas=[];s.docs[2].tutorAulas=['2|A'];s.tables.get('DocentesAcceso').rows[1][2]=JSON.stringify(s.docs);s.cacheEntries.clear();assert.equal(s.load('admin').exportable,false);assert.equal(process(s).ok,false);assert.equal(JSON.stringify(s.tables.get('TransversalesProcesado').rows),old);});
test('JS contains no duplicate named top-level functions after adding Admin flow',()=>{for(const file of ['apps-script/Codigo.js','transversales-client.js','registro-transversales.js']){const names=[...read(file).matchAll(/^function (\w+)\(/gm)].map(m=>m[1]);assert.equal(names.length,new Set(names).size,file);}});
test('selecting, customizing and editing a conclusion persists final textarea text, never an option ID',()=>{const c=vm.createContext({window:{}});vm.runInContext(read('conclusion-suggestions.js'),c);let stored='',focused=false;const field={value:'',readOnly:false,disabled:false,oninput(){stored=this.value;},focus(){focused=true;}},select={value:'',closest:()=>({querySelector:()=>field})};c.window.IEConclusionSuggestions.bind({querySelectorAll:()=>[select]});select.value=c.window.IEConclusionSuggestions.suggestions('TIC')[0];select.onchange();assert.equal(stored,select.value);field.value+=' Texto editado.';field.oninput();assert.match(stored,/Texto editado/);const old=stored;select.value='custom';select.onchange();assert.equal(stored,old);assert.equal(field.value,old);assert.equal(focused,true);field.readOnly=true;select.value='Forbidden';select.onchange();assert.equal(stored,old);});
test('Resumen updates the same two transversal cells without appending a second table',async()=>{const src=read('tests/registro-transversales-integracion.test.cjs'),ui=new Function('require','__dirname',src.split('\ntest(')[0]+'\nreturn ui;')(require,__dirname),f=ui(),root=f.el('summary');f.api.summary(root);assert.equal(root.children.length,1);const table=root.children[0],rows=table.querySelectorAll('tbody tr'),before=[...rows[0].children];assert.equal(before.length,2);await f.api.load();f.api.summary(root);f.api.setDirect(f.api.current(),f.s.id,'tic',{modo:'letra',valor:'B'});f.api.summary(root);assert.equal(root.children[0],table);assert.equal(rows[0].children.length,2);assert.equal(rows[0].children[0],before[0]);assert.match(table.innerHTML,/Promedio referencial.*TIC.*Gestiona su aprendizaje/s);assert.match(before[0].innerHTML,/B/);});
test('worker v14 precaches coupled Admin, Registro, transversal UI and suggestion JS without private API data',async()=>{const src=read('tests/service-worker-static.test.cjs'),setup=new Function('require','__dirname',src.split('\ntest(')[0]+'\nreturn fixture;')(require,__dirname),s=setup();await s.dispatch('install');assert.ok(s.stores.has('matriz-ie22375-v14'));s.network(async()=>{throw Error('offline');});for(const resource of ['admin.html','registro.html','transversales.html','conclusion-suggestions.js']){const response=await s.dispatch('fetch',{request:s.request(resource)});assert.equal(response.ok,true);if(resource.endsWith('.js'))assert.match(response.headers.get('Content-Type'),/javascript/);}assert.doesNotMatch(read('sw.js'),/cache\.put\([^\n]*loadtransversal/);});
test('interrupted processing fails closed without silently promoting an incomplete snapshot',()=>{const s=approved(),old=s.load('admin').procesado;review(s);const sh=s.tables.get('TransversalesConsolidado'),append=sh.appendRow;sh.appendRow=()=>{throw Error('Synthetic append interruption');};const out=process(s);assert.equal(out.ok,false);sh.appendRow=append;assert.equal(s.route('loadtransversalexport','admin').exportable,false);assert.ok(s.tables.get('TransversalesProcesado').rows.some(row=>String(row[6]).includes(String(old.ts))));});
test('Admin cannot process foreign/unknown student decisions or client-supplied review audit',()=>{const s=fixture(),data=s.load('admin');const before=s.state.writes;assert.equal(s.route('savetransversalfinal','admin',{version:0,versionAportes:data.versionAportes,finales:{'id:foreign':{tic:{modo:'letra',valor:'A'}}}}).ok,false);assert.equal(s.state.writes,before);s.final('admin','A');const now=s.load('admin');assert.equal(s.route('procesartransversales','admin',{version:now.version,versionAportes:now.versionAportes,revisado:{admin:'admin',tutor:{user:'math'}},revisadoConTutor:true}).ok,false);});
function generalFixture(){
 const html=read('admin.html'),start=html.indexOf('async function renderRegistroGeneral('),code=html.slice(start,html.indexOf('\n}',start)+2),elements=new Map();
 function node(tag){return {tagName:tag,value:'',textContent:'',children:[],appendChild(x){this.children.push(x);if(tag==='select'&&!this.value)this.value=x.value;return x;},replaceChildren(){this.children=[];}};}
 const el=id=>{if(!elements.has(id))elements.set(id,node(id==='generalAula'?'select':'div'));return elements.get(id);};el('generalBim').value='I';
 const c=vm.createContext({document:{getElementById:el,createElement:node},studentKey:a=>'id:'+a.idSiagie,IEStudents:{loadRoster:async()=>({secundaria:{estudiantes:[{nombre:'Synthetic Student',idSiagie:'one',grado:2,seccion:'A'}]}})},IERegistroAcademico:{catalog:{secundaria:{Matemática:['Synthetic competence']}}},fetchRegAula:async()=>[{area:'Matemática',payload:{}}],letraDesdePayload:()=> 'A',concDesdePayload:()=>'',IETransversales:{request:async()=>({exportable:true,resultados:{'id:one':{tic:{listo:true,final:{nivel:'A'}},autonomia:{listo:true,final:{nivel:'C',conclusion:'Approved final conclusion'}}}}})}});vm.runInContext(code,c);return {c,el};
}
test('Registro General uses academic records and only processed transversal finals, with complete aula status',async()=>{const f=generalFixture();await f.c.renderRegistroGeneral();assert.match(f.el('generalStatus').textContent,/1\/1 completas.*Procesadas.*Completo/);const table=f.el('generalRows').children.at(-1);assert.equal(table.children[1].children[2].textContent,'C · Approved final conclusion');});
test('Registro General labels missing academics/unprocessed transversals incomplete instead of using suggestions',async()=>{const f=generalFixture();f.c.fetchRegAula=async()=>[];f.c.IETransversales.request=async()=>({exportable:false,resultados:{'id:one':{tic:{listo:false,final:{nivel:'AD'}},autonomia:{listo:false,final:{nivel:'AD'}}}}});await f.c.renderRegistroGeneral();assert.match(f.el('generalStatus').textContent,/0\/1 completas.*Pendientes.*Incompleto/);assert.equal(f.el('generalRows').children.at(-1).children[1].children[1].textContent,'Pendiente de procesamiento');});
test('Registro General rejects offline roster as production verification and discards older context responses',async()=>{const f=generalFixture();f.c.IEStudents.loadRoster=async()=>({offline:true});await f.c.renderRegistroGeneral();assert.match(f.el('generalStatus').textContent,/requiere verificación actual/);});
for(const kind of ['missing','expired','altered'])test('new processing route rejects '+kind+' token without writes',()=>{const s=fixture(),token=kind==='missing'?'':kind==='altered'?s.admin+'x':s.token('admin','admin',{exp:Date.now()-1});const before=s.state.writes;assert.equal(s.post({action:'procesartransversales',token,...s.ctx,role:'admin',revisadoConTutor:true}).ok,false);assert.equal(s.state.writes,before);});
