const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),clone=x=>JSON.parse(JSON.stringify(x)),source=read('tests/transversales.test.cjs');
const {fixture,client}=new Function('require','__dirname',source.split('\ntest(')[0]+'\nreturn {fixture,client};')(require,__dirname);
const ui=new Function('require','__dirname',read('tests/registro-transversales-integracion.test.cjs').split('\ntest(')[0]+'\nreturn ui;')(require,__dirname);
function config(s){s.tables.get('DocentesAcceso').rows[1][2]=JSON.stringify(s.docs);s.cacheEntries.clear();}
function official(s=fixture()){s.final('math','A');assert.equal(s.confirm('math','procesartransversales').ok,true);return s;}
function extract(file,name){const src=read(file),i=src.indexOf('function '+name+'(');return src.slice(i,src.indexOf('\n}',i)+2);}

test('A teacher may tutor multiple classrooms without teaching academic areas in all of them',()=>{
 const s=fixture();s.docs[1].tutorAulas=['2|A','2|B'];config(s);assert.deepEqual(clone(s.route('loadtransversalesaulas','math').aulas),['2|A','2|B']);
 const b=s.route('loadtransversales','math',{seccion:'B',area:''});assert.equal(b.ok,true);assert.deepEqual(clone(b.estudiantes.map(a=>a.id)),['id:synthetic-b']);assert.equal(b.puedeFinal,true);assert.equal(s.route('savereg','math',{seccion:'B',area:'Matemática',payload:{}}).ok,false);
});
test('Frontend rejects a duplicate active Tutor before saving or uploading configuration',()=>{
 const alerts=[],values={docEditId:'',docUser:'new-teacher',docPass:'synthetic-only',docNombre:'Synthetic New Teacher',docNivel:'secundaria'},c=vm.createContext({document:{getElementById:id=>({value:values[id],checked:id==='docEsTutor'}),querySelectorAll:sel=>sel.includes('doc-area')?[{value:'Matemática'}]:sel.includes('doc-tutor')?[{value:'2|A'}]:[]},alert:m=>alerts.push(m),leerAsignacionesFormulario:()=>({'Matemática':['2|A']}),leerAportesFormulario:()=>({}),loadDocentes:()=>[{id:'existing',activo:true,tutorAulas:['2|A']}],saveDocentes:()=>assert.fail('Must not save'),subirDocentesNube:()=>assert.fail('Must not upload')});vm.runInContext(extract('admin.html','guardarDocente'),c);c.guardarDocente();assert.deepEqual(alerts,['Ya hay un tutor activo en esa aula']);
});
test('Backend rejects canonical duplicate active tutor assignments, even from manipulated Admin form',()=>{
 const s=fixture();s.docs[2].tutorAulas=['2|a'];const before=s.state.writes;const out=s.post({action:'savedoc',token:s.admin,docentes:s.docs});assert.equal(out.ok,false);assert.match(out.error,/un tutor activo/);assert.equal(s.state.writes,before);
});
test('Inactive Tutor does not create co-tutoring; one Tutor may retain several classes',()=>{
 const s=fixture();s.docs[1].tutorAulas=['2|A','2|B'];s.docs[2].tutorAulas=['2|A'];s.docs[2].activo=false;assert.equal(s.post({action:'savedoc',token:s.admin,docentes:s.docs}).ok,true);
});
test('Tutor A cannot read, decide or issue official data in Tutor B classroom',()=>{
 const s=fixture();s.docs[4].tutorAulas=['2|B'];config(s);for(const action of ['loadtransversales','savetransversalfinal','procesartransversales'])assert.equal(s.route(action,'math',{seccion:'B',area:'',tutorAulas:['2|B'],role:'admin'}).code,'DENIED');
});
for(const year of [2026,2027])for(const flag of [true,false,undefined])test('Server assignment, not year or envioIntegral, requires contribution '+year+'/'+flag,()=>{
 const s=fixture();s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:year,bimestres:{I:'abierto'}});const req={action:'savereg',token:s.token('math'),nivel:'secundaria',bimestre:'I',grado:2,seccion:'A',area:'Matemática',payload:{},envioIntegral:flag,anio:2026,role:'admin',aportesObligatorios:false};assert.equal(s.post(req).ok,false);assert.equal(s.aporte('math','A').ok,true);assert.equal(s.post(req).ok,true);
});
for(const year of [2026,2027])test('Unassigned teacher can submit academic area normally in '+year,()=>{
 const s=fixture();delete s.docs[1].aportesTransversales;config(s);s.tables.get('ConfigSistema').rows[1][2]=JSON.stringify({anio:year,bimestres:{I:'abierto'}});assert.equal(s.post({action:'savereg',token:s.token('math'),nivel:'secundaria',bimestre:'I',grado:2,seccion:'A',area:'Matemática',payload:{}}).ok,true);assert.equal(s.aporte('math','A').code,'DENIED');
});
test('Unassigned teacher sees no transversal selectors, columns or obligatory contribution',async()=>{
 const f=ui();f.c.getLoginSession=()=>({role:'docente',user:'math',aportesTransversales:{}});assert.equal(f.api.eligible(),false);assert.equal(f.c.competenciasParaEvaluar().length,1);await f.api.load();assert.equal(f.calls.length,0);assert.equal(await f.api.syncForUpload(),true);const root=f.el('summary');f.api.summary(root);assert.doesNotMatch(root.children[0].innerHTML,/data-trans-summary/);
});
test('Explicit assignment shows two competencies but does not expand academic competencies',()=>{const f=ui();assert.equal(f.api.eligible(),true);assert.equal(f.c.competenciasParaEvaluar().length,3);assert.equal(f.c.competencias().length,1);f.c.seccion='B';assert.equal(f.api.eligible(),false);assert.equal(f.c.competenciasParaEvaluar().length,1);});
test('Tutorship alone does not enable own area contribution or count it as missing',()=>{
 const s=fixture();delete s.docs[1].aportesTransversales;config(s);const out=s.load('math');assert.equal(out.puedeFinal,true);assert.ok(!out.areas.includes('Matemática'));assert.ok(!out.resultados[s.id].tic.resumen.sinAporte.includes('Matemática'));assert.equal(s.aporte('math','A').code,'DENIED');assert.equal(s.aporte('communication','B').ok,true);assert.equal(s.load('math').aportes[0].user,'communication');
});
test('Assigned Tutor own area and every other assigned teacher remain visible; suggestion retains one vote per area',()=>{
 const s=fixture();s.docs.push({user:'math2',nombre:'Synthetic Math 2',nivel:'secundaria',asignaciones:{'Matemática':['2|A']},aportesTransversales:{'Matemática':['2|A']}});config(s);s.aporte('math','A');s.aporte('communication','B');s.aporte('math2','AD');const out=s.load('math');assert.equal(out.aportes.length,3);assert.equal(out.resultados[s.id].tic.resumen.recibidos,2);assert.equal(out.resultados[s.id].tic.resumen.conteo.AD,1);
});
test('Removing assignment excludes old contribution without deleting history and invalidates snapshot',()=>{
 const s=fixture();s.aporte('communication','B');official(s);const rows=JSON.stringify(s.tables.get('TransversalesAportes').rows);delete s.docs[2].aportesTransversales;config(s);const out=s.load('math');assert.equal(out.exportable,false);assert.equal(out.aportes.length,0);assert.ok(!out.resultados[s.id].tic.resumen.sinAporte.includes('Comunicación'));assert.equal(JSON.stringify(s.tables.get('TransversalesAportes').rows),rows);
});
test('Server rejects contribution assignment outside actual academic area/class',()=>{
 for(const map of [{'Matemática':['2|B']},{'Comunicación':['2|A']},{'Competencias Transversales':['2|A']}]){const s=fixture();s.docs[1].aportesTransversales=map;assert.equal(s.post({action:'savedoc',token:s.admin,docentes:s.docs}).ok,false);}
});
for(const level of ['AD','A','B','C'])test('Tutor official '+level+' has conclusion requirement only for C',()=>{
 const s=fixture();s.final('math',level);const out=s.confirm('math','procesartransversales');assert.equal(out.ok,level!=='C');if(level==='C'){s.final('math','C',undefined,undefined,'Synthetic personalized conclusion');assert.equal(s.confirm('math','procesartransversales').ok,true);}
});
for(const action of ['savetransversalfinal','revisartransversal','procesartransversales'])test('Admin cannot '+action+' even with forged Tutor identity/configuration',()=>{
 const s=fixture(),data=s.load('admin'),writes=s.state.writes;const out=s.route(action,'admin',{user:'math',role:'docente',tutorAulas:['2|A'],version:data.version,versionAportes:data.versionAportes,finales:{[s.id]:{tic:{modo:'letra',valor:'A'}}}});assert.equal(out.code,'DENIED');assert.equal(s.state.writes,writes);
});
test('New snapshot contains server-derived Tutor/aula/bim/competence/timestamp/version audit and no Admin decision',()=>{
 const s=official(),out=s.load('admin'),p=out.procesado,f=p.finales[s.id].tic;assert.equal(p.schema,3);assert.equal(p.flujo,'tutor');assert.equal(p.tutorUser,'math');assert.equal(f.tutorUser,'math');assert.equal(f.aula,'2|A');assert.equal(f.bimestre,'I');assert.equal(f.competencia,'tic');assert.equal(f.versionAportes,out.versionAportes);assert.ok(f.ts>0);assert.equal(p.admin,undefined);assert.equal(out.puedeFinal,false);assert.equal(out.puedeProcesar,false);assert.equal(s.route('loadtransversalexport','admin').exportable,true);
});
test('Legacy Admin snapshot remains historical, cannot enter SIAGIE, and requires a new Tutor decision',()=>{
 const s=fixture(),d=s.load('admin'),old={schema:2,finales:{[s.id]:{tic:{modo:'letra',valor:'A',nivel:'A'}}},versionAportes:d.versionAportes,admin:'admin'};s.c.transversalAppend_('TransversalesConsolidado',['secundaria||I||2||A','I',2,'A',d.versionAportes,100,JSON.stringify(old)]);s.c.transversalAppend_('TransversalesProcesado',['secundaria||I||2||A','I',2,'A',d.versionAportes,100,JSON.stringify({...old,revision:{tutor:{user:'math'}},version:100})]);const rows=JSON.stringify(s.tables.get('TransversalesProcesado').rows);assert.equal(s.route('loadtransversalexport','admin').exportable,false);assert.equal(s.load('admin').historico.admin,'admin');official(s);assert.equal(s.load('admin').exportable,true);assert.ok(JSON.stringify(s.tables.get('TransversalesProcesado').rows).startsWith(rows.slice(0,-1)));
});
test('Teacher contribution after official send leaves immutable snapshot unchanged and makes export pending',()=>{
 const s=official(),rows=JSON.stringify(s.tables.get('TransversalesProcesado').rows);s.aporte('math','B');const out=s.route('loadtransversalexport','admin');assert.equal(out.exportable,false);assert.equal(out.resultados[s.id].tic.final,null);assert.equal(JSON.stringify(s.tables.get('TransversalesProcesado').rows),rows);assert.equal(s.confirm('math','procesartransversales').ok,false);s.final('math','B');assert.equal(s.confirm('math','procesartransversales').ok,true);
});
test('Changing active Tutor invalidates old snapshot and rejects previous Tutor despite forged client roles',()=>{
 const s=official();s.docs[1].tutorAulas=[];s.docs[2].tutorAulas=['2|A'];config(s);assert.equal(s.load('admin').exportable,false);assert.equal(s.confirm('math','procesartransversales').code,'DENIED');s.final('communication','A');assert.equal(s.confirm('communication','procesartransversales').ok,true);assert.equal(s.load('admin').procesado.tutorUser,'communication');
});
test('Tutor decisiones cannot include a student outside the private roster',()=>{const s=fixture(),d=s.load('math');assert.equal(s.route('savetransversalfinal','math',{version:d.version,versionAportes:d.versionAportes,finales:{'id:synthetic-b':{tic:{modo:'letra',valor:'A'}}}}).ok,false);});
test('Register Tutor entry is separate from academic context and hides previous academic upload controls',()=>{const html=read('registro.html');assert.match(html,/id="registroTutorPanel" hidden/);assert.match(html,/id="registroAcademicoPanel"/);assert.match(extract('registro.html','abrirTutorRegistro'),/registroAcademicFooter.*hidden=true/);assert.doesNotMatch(extract('registro.html','abrirTutorRegistro'),/areaActual\s*=/);assert.match(extract('registro.html','renderAreas'),/ses.tutorAulas/);assert.match(extract('registro.html','setArea'),/tutorRegistroController.clear/);});
test('Frontend session retains explicit tutor classrooms and contribution map from protected profile',()=>{const html=read('index.html');assert.match(html,/tutorAulas: perfil.tutorAulas \|\| \[\]/);assert.match(html,/aportesTransversales: perfil.aportesTransversales \|\| \{\}/);});
test('Backend login profile exposes only own Tutor and explicit contribution scope',()=>{const s=fixture();s.docs[1].tutorAulas=['2|A','2|B'];config(s);const out=s.post({action:'login',tipo:'docente',usuario:'math',password:'synthetic-only'});assert.equal(out.ok,true);assert.deepEqual(clone(out.tutorAulas),['2|A','2|B']);assert.deepEqual(clone(out.aportesTransversales),{'Matemática':['2|A']});assert.doesNotMatch(JSON.stringify(out),/Synthetic Communication|synthetic-only/);});

function mounted(initialTransport){
 const server=fixture();server.docs[1].tutorAulas=['2|A','2|B'];config(server);
 const f=client('docente'),elBase=new Function(source.slice(source.indexOf('function dom(){'),source.indexOf("test('real evidence grid"))+'\nreturn dom;')()(),nodes=new Map(),events={};
 function node(tag){const el=elBase(tag),append=el.appendChild;el.appendChild=function(n){append.call(this,n);if(tag==='select'&&this.children.length===1)this.value=n.value;return n;};return el;}
 const el=id=>{if(!nodes.has(id))nodes.set(id,node(id==='transAula'||id==='transBim'?'select':'div'));return nodes.get(id);};
 f.c.document.createElement=node;f.c.document.getElementById=el;f.c.window.addEventListener=(name,fn)=>events[name]=fn;f.c.window.removeEventListener=(name,fn)=>{if(events[name]===fn)delete events[name];};
 const token=server.token('math');let current=token,transport=initialTransport|| (async body=>server.post(body));f.c.window.IEStudents.validToken=()=>current;f.c.window.IEStudents.fetchJSON=async(url,opts)=>transport(JSON.parse(opts.body));
 f.run(read('transversales-client.js'));const controller=f.c.window.IETransversales.init();return {server,f,el,events,controller,transport:fn=>transport=fn,token:v=>current=v};
}
test('Embedded Tutor controller loads only selected authorized classroom and separates its students',async()=>{const m=mounted();await m.controller.ready;assert.match(m.el('transRows').querySelectorAll('th').map(n=>n.textContent).join(' '),/Synthetic Student A/);m.el('transAula').value='2|B';await m.el('transAula').onchange();const text=m.el('transRows').querySelectorAll('th').map(n=>n.textContent).join(' ');assert.match(text,/Synthetic Student B/);assert.doesNotMatch(text,/Synthetic Student A/);});
test('Late response from another Tutor classroom cannot replace current rows',async()=>{const m=mounted();await m.controller.ready;let resolve; m.transport(body=>body.action==='loadtransversales'&&body.seccion==='A'?new Promise(r=>resolve=()=>r(m.server.post(body))):Promise.resolve(m.server.post(body)));const older=m.el('transReload').onclick();await new Promise(r=>setImmediate(r));m.el('transAula').value='2|B';await m.el('transAula').onchange();resolve();await older;assert.match(m.el('transRows').querySelectorAll('th').map(n=>n.textContent).join(' '),/Synthetic Student B/);});
test('Disposed Tutor mount discards pending aula metadata and does not render into the next view',async()=>{const m=mounted();m.controller.clear();await m.controller.ready;assert.equal(m.el('transRows').children.length,0);});
test('Tutor draft prevents accidental departure and raises beforeunload without saving automatically',async()=>{const m=mounted();await m.controller.ready;const select=m.el('transRows').querySelectorAll('select')[1];select.value='A';select.onchange();m.f.c.confirm=()=>false;assert.equal(m.controller.canLeave(),false);let warned=false;m.events.beforeunload({preventDefault:()=>warned=true});assert.equal(warned,true);assert.equal(m.server.tables.has('TransversalesConsolidado'),false);});
test('Explicit SESSION rejection during Tutor refresh clears private rows and permits relogin',async()=>{const m=mounted();await m.controller.ready;m.transport(async()=>({ok:false,code:'SESSION',error:'Synthetic revoked session'}));await m.el('transReload').onclick();assert.equal(m.el('transRows').children.length,0);assert.match(m.el('transStatus').textContent,/revoked/);});
test('Changed token cannot accept a late Tutor response or leave old private rows visible',async()=>{const m=mounted();await m.controller.ready;let resolve;m.transport(body=>new Promise(r=>resolve=()=>r(m.server.post(body))));const pending=m.el('transReload').onclick();await new Promise(r=>setImmediate(r));m.token('changed-token');resolve();await pending;assert.equal(m.el('transRows').children.length,0);assert.match(m.el('transStatus').textContent,/sesión cambió/);});
test('Tutor edit view displays every assigned teacher of the same area, while preserving suggestion method',()=>{const m=mounted(),s=m.server;s.docs.push({user:'math2',nombre:'Synthetic Math 2',nivel:'secundaria',asignaciones:{'Matemática':['2|A']},aportesTransversales:{'Matemática':['2|A']}});config(s);s.aporte('math','A');s.aporte('math2','B');const box=m.el('allContributors');m.f.c.window.IETransversales.editor(box,clone(s.load('math')),s.ctx,true);const messages=box.querySelectorAll('p').map(n=>n.textContent).join(' ');assert.match(messages,/Matemática · Synthetic Math: 15 → A/);assert.match(messages,/Matemática · Synthetic Math 2: 12 → B/);assert.equal(s.load('math').resultados[s.id].tic.resumen.recibidos,1);m.controller.clear();});

test('Old Admin backend cannot enable decision controls in the new Tutor interface',()=>{const m=mounted(),data=clone(m.server.load('admin'));delete data.flujoTutor;data.flujoAdmin=true;data.puedeFinal=true;data.puedeProcesar=true;const box=m.el('legacyBackend');m.f.c.window.IETransversales.editor(box,data,m.server.ctx,true);assert.equal(box.querySelectorAll('button').length,0);assert.equal(box.querySelectorAll('textarea').length,0);assert.match(box.querySelectorAll('p').map(n=>n.textContent).join(' '),/Backend anterior/);m.controller.clear();});
test('Admin consultation contains final text but no decision input or descriptive conclusion form',()=>{const m=mounted();m.server.final('math','C',undefined,undefined,'Synthetic official Tutor conclusion');const box=m.el('adminReadOnly');m.f.c.window.IETransversales.editor(box,clone(m.server.load('admin')),m.server.ctx,true);assert.equal(box.querySelectorAll('textarea').length,0);assert.equal(box.querySelectorAll('button').length,0);assert.match(box.querySelectorAll('p').map(n=>n.textContent).join(' '),/Conclusión del Tutor: Synthetic official Tutor conclusion/);m.controller.clear();});

test('Malformed existing co-tutor configuration cannot authorize an official write',()=>{const s=fixture();s.docs[2].tutorAulas=['2|A'];config(s);assert.equal(s.load('math').puedeFinal,false);assert.equal(s.final('math','A').code,'DENIED');assert.equal(s.confirm('math','procesartransversales').code,'DENIED');});
test('Disposed controller metadata failure cannot rebind the next view retry button',async()=>{let reject;const m=mounted(()=>new Promise((r,j)=>reject=j));m.controller.clear();const next=()=>{};m.el('transReload').onclick=next;reject(Error('Synthetic metadata failure'));await m.controller.ready;assert.equal(m.el('transReload').onclick,next);assert.equal(m.el('transRows').children.length,0);});
